import { createFileRoute } from "@tanstack/react-router";
import { useQuery, useQueryClient } from "@tanstack/react-query";
import { useServerFn } from "@tanstack/react-start";
import { AppShell, PageBody, PageHeader } from "@/components/app-shell";
import { Card } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { useOrgId } from "@/hooks/use-current-org";
import {
  listInsights,
  updateInsightStatus,
  getInsightSummary,
} from "@/lib/accounting/ai-controller.functions";
import { Brain, CheckCircle2, XCircle, ShieldAlert } from "lucide-react";
import { toast } from "sonner";

export const Route = createFileRoute("/close/ai-assistant")({
  head: () => ({
    meta: [
      { title: "AI Controller — LedgerOS" },
      {
        name: "description",
        content:
          "Advisory-only accounting intelligence. Explains what happened, why, evidence, and confidence. Never posts entries.",
      },
      { property: "og:title", content: "AI Controller — LedgerOS" },
    ],
  }),
  component: AiControllerPage,
});

const PERSONA_LABELS: Record<string, string> = {
  controller: "AI Controller",
  close_assistant: "Close Assistant",
  accountant_assistant: "Accountant Assistant",
};

function AiControllerPage() {
  const orgId = useOrgId();
  const qc = useQueryClient();
  const list = useServerFn(listInsights);
  const upd = useServerFn(updateInsightStatus);
  const sum = useServerFn(getInsightSummary);

  const insights = useQuery({
    queryKey: ["insights", orgId],
    queryFn: () => list({ data: { orgId: orgId!, persona: "all", status: "open", limit: 100 } }),
    enabled: !!orgId,
  });
  const summary = useQuery({
    queryKey: ["insights-summary", orgId],
    queryFn: () => sum({ data: { orgId: orgId! } }),
    enabled: !!orgId,
  });

  async function handle(id: string, status: "acknowledged" | "dismissed" | "resolved") {
    if (!orgId) return;
    try {
      await upd({ data: { id, orgId, status } });
      toast.success(`Insight ${status}`);
      qc.invalidateQueries({ queryKey: ["insights", orgId] });
      qc.invalidateQueries({ queryKey: ["insights-summary", orgId] });
    } catch (e) {
      toast.error(e instanceof Error ? e.message : "Failed to update");
    }
  }

  return (
    <AppShell>
      <PageHeader
        eyebrow="LedgerOS · Accounting Intelligence"
        title="AI Controller"
        description="Advisory-only intelligence. Every insight explains what happened, why, evidence, confidence, and a recommended human action. AI cannot post entries, change accounting, approve transactions, or override controls."
      />
      <PageBody>
        {!orgId ? (
          <Card className="p-6 text-sm text-muted-foreground">
            Sign in to view accounting intelligence.
          </Card>
        ) : (
          <div className="space-y-6">
            <Card className="border-amber-500/40 bg-amber-500/5 p-4">
              <div className="flex items-start gap-3">
                <ShieldAlert className="mt-0.5 h-5 w-5 text-amber-500" />
                <div className="text-sm">
                  <p className="font-medium">Advisory-only layer</p>
                  <p className="text-muted-foreground">
                    Insights are immutable records generated by scheduled server processes. The AI
                    never writes to journal entries, approves transactions, or alters fiscal state.
                    All accounting actions still flow through the accounting engine with human
                    approval.
                  </p>
                </div>
              </div>
            </Card>

            <div className="grid gap-3 md:grid-cols-4">
              <Card className="p-3">
                <div className="text-[11px] uppercase text-muted-foreground">Open insights</div>
                <div className="mt-1 text-2xl font-semibold tabular-nums">
                  {summary.data?.byStatus.open ?? 0}
                </div>
              </Card>
              <Card className="p-3">
                <div className="text-[11px] uppercase text-muted-foreground">Avg confidence</div>
                <div className="mt-1 text-2xl font-semibold tabular-nums">
                  {summary.data ? Math.round(summary.data.avgConfidence * 100) : 0}%
                </div>
              </Card>
              <Card className="p-3">
                <div className="text-[11px] uppercase text-muted-foreground">Acknowledged</div>
                <div className="mt-1 text-2xl font-semibold tabular-nums">
                  {summary.data?.byStatus.acknowledged ?? 0}
                </div>
              </Card>
              <Card className="p-3">
                <div className="text-[11px] uppercase text-muted-foreground">Resolved</div>
                <div className="mt-1 text-2xl font-semibold tabular-nums">
                  {summary.data?.byStatus.resolved ?? 0}
                </div>
              </Card>
            </div>

            <div className="space-y-3">
              {insights.data?.map((i) => (
                <Card key={i.id} className="p-4">
                  <div className="flex items-start justify-between gap-3">
                    <div className="min-w-0 flex-1">
                      <div className="mb-1 flex items-center gap-2 flex-wrap">
                        <Brain className="h-4 w-4 text-indigo-500" />
                        <Badge variant="secondary">{PERSONA_LABELS[i.persona] ?? i.persona}</Badge>
                        <Badge variant="outline">{i.category}</Badge>
                        <span className="text-[11px] text-muted-foreground">
                          Confidence:{" "}
                          <span className="font-medium text-foreground">
                            {Math.round(Number(i.confidence) * 100)}%
                          </span>
                        </span>
                      </div>
                      <h3 className="text-sm font-semibold">{i.title}</h3>
                      <p className="mt-1 text-sm">
                        <span className="font-medium">What happened: </span>
                        <span className="text-muted-foreground">{i.what_happened}</span>
                      </p>
                      {i.why && (
                        <p className="mt-1 text-sm">
                          <span className="font-medium">Why: </span>
                          <span className="text-muted-foreground">{i.why}</span>
                        </p>
                      )}
                      {i.recommended_action && (
                        <p className="mt-1 text-sm">
                          <span className="font-medium">Recommended action: </span>
                          <span className="text-muted-foreground">{i.recommended_action}</span>
                        </p>
                      )}
                      {Array.isArray(i.evidence) && i.evidence.length > 0 && (
                        <details className="mt-2 text-xs">
                          <summary className="cursor-pointer text-muted-foreground">
                            Evidence ({i.evidence.length})
                          </summary>
                          <pre className="mt-1 overflow-x-auto rounded bg-muted/40 p-2 text-[11px]">
                            {JSON.stringify(i.evidence, null, 2)}
                          </pre>
                        </details>
                      )}
                    </div>
                    <div className="flex shrink-0 flex-col gap-2">
                      <Button
                        size="sm"
                        variant="outline"
                        onClick={() => handle(i.id, "acknowledged")}
                      >
                        <CheckCircle2 className="mr-1 h-3.5 w-3.5" /> Acknowledge
                      </Button>
                      <Button size="sm" variant="outline" onClick={() => handle(i.id, "resolved")}>
                        Resolve
                      </Button>
                      <Button size="sm" variant="ghost" onClick={() => handle(i.id, "dismissed")}>
                        <XCircle className="mr-1 h-3.5 w-3.5" /> Dismiss
                      </Button>
                    </div>
                  </div>
                </Card>
              ))}
              {!insights.isLoading && (insights.data?.length ?? 0) === 0 && (
                <Card className="p-6 text-center text-sm text-muted-foreground">
                  No open advisory insights. The AI Controller runs on a scheduled cadence and will
                  surface findings here.
                </Card>
              )}
            </div>
          </div>
        )}
      </PageBody>
    </AppShell>
  );
}
