import { createServerFn } from "@tanstack/react-start";
import { z } from "zod";
import { requireSupabaseAuth } from "@/integrations/supabase/auth-middleware";

/**
 * M8 — Accounting Intelligence (advisory only)
 *
 * Insights are READ-ONLY except for status transitions (acknowledged /
 * dismissed / resolved). A DB trigger enforces immutability of the
 * narrative, evidence, confidence, and advisory_only flag. Insights are
 * generated by a scheduled server process (service_role) — never
 * inserted from the client — so end users can only observe and
 * acknowledge, never fabricate.
 *
 * AI CANNOT:
 *  - post journal entries
 *  - change accounting records
 *  - approve transactions
 *  - override controls
 */

const orgOnly = z.object({ orgId: z.string().uuid() });

export const listInsights = createServerFn({ method: "GET" })
  .middleware([requireSupabaseAuth])
  .inputValidator((v) =>
    z.object({
      orgId: z.string().uuid(),
      persona: z.enum(["controller","close_assistant","accountant_assistant","all"]).default("all"),
      status: z.enum(["open","acknowledged","dismissed","resolved","all"]).default("open"),
      limit: z.number().int().min(1).max(200).default(100),
    }).parse(v),
  )
  .handler(async ({ data, context }) => {
    let q = context.supabase
      .from("accounting_insights")
      .select("*")
      .eq("org_id", data.orgId)
      .order("created_at", { ascending: false })
      .limit(data.limit);
    if (data.persona !== "all") q = q.eq("persona", data.persona);
    if (data.status !== "all") q = q.eq("status", data.status);
    const { data: rows, error } = await q;
    if (error) throw new Error(error.message);
    return rows ?? [];
  });

export const updateInsightStatus = createServerFn({ method: "POST" })
  .middleware([requireSupabaseAuth])
  .inputValidator((v) =>
    z.object({
      id: z.string().uuid(),
      orgId: z.string().uuid(),
      status: z.enum(["open","acknowledged","dismissed","resolved"]),
    }).parse(v),
  )
  .handler(async ({ data, context }) => {
    const patch: {
      status: string;
      acknowledged_by?: string;
      acknowledged_at?: string;
    } = { status: data.status };
    if (data.status === "acknowledged") {
      patch.acknowledged_by = context.userId;
      patch.acknowledged_at = new Date().toISOString();
    }
    const { error } = await context.supabase
      .from("accounting_insights")
      .update(patch)
      .eq("id", data.id)
      .eq("org_id", data.orgId);
    if (error) throw new Error(error.message);
    return { ok: true };
  });

/**
 * Summary counts for the accountant dashboard. Advisory metrics only.
 */
export const getInsightSummary = createServerFn({ method: "GET" })
  .middleware([requireSupabaseAuth])
  .inputValidator((v) => orgOnly.parse(v))
  .handler(async ({ data, context }) => {
    const { data: rows, error } = await context.supabase
      .from("accounting_insights")
      .select("persona, status, confidence")
      .eq("org_id", data.orgId);
    if (error) throw new Error(error.message);
    const summary = {
      total: rows?.length ?? 0,
      byStatus: {} as Record<string, number>,
      byPersona: {} as Record<string, number>,
      avgConfidence: 0,
    };
    let confSum = 0;
    for (const r of rows ?? []) {
      summary.byStatus[r.status] = (summary.byStatus[r.status] ?? 0) + 1;
      summary.byPersona[r.persona] = (summary.byPersona[r.persona] ?? 0) + 1;
      confSum += Number(r.confidence);
    }
    summary.avgConfidence = summary.total > 0 ? confSum / summary.total : 0;
    return summary;
  });
