/**
 * 6B-2 mock data. Demonstration only — no real compensation.
 */

import type {
  AttributionConflict,
  AttributionEvidence,
  CompensationAttribution,
  CompensationParticipant,
  CompensationPlan,
  CompensationPlanParticipant,
  CompensationPlanVersion,
} from "./domain-types";
import { resolveCompensationPolicy } from "./policy-defaults";
import { DEFAULT_FAMILY_DISBURSEMENT_CLASS } from "./types";

const now = "2026-07-13T14:00:00Z";

export const MOCK_PLANS: CompensationPlan[] = [
  {
    id: "cp_std_sales",
    name: "Standard Sales Pool — 10% Collected",
    description: "Core sales plan. 10% pool on collected & cleared CCA service revenue.",
    family: "sales_commission",
    disbursementClass: DEFAULT_FAMILY_DISBURSEMENT_CLASS.sales_commission,
    basis: "collected_and_cleared_nrsr",
    defaultRate: 0.1,
    formulaText: "10% × (collected NRSR − pass-through − refunds − chargebacks − credits)",
    effectiveDate: "2026-01-01",
    participantCount: 5,
    eligibleServices: ["Compliance Onboarding", "Advisory Retainer"],
    eligibleProducts: [],
    eligibleApps: ["CCA Suite"],
    eligibleDepartments: ["Sales"],
    eligibleChannels: ["Direct"],
    eligibleEntities: ["CCA LLC"],
    eligibleCustomerTypes: ["Standard", "Renewal"],
    geographicScope: ["US"],
    houseAccountRule: "suppress",
    survivalMonths: 12,
    passThroughTreatment: "excluded",
    collectionRequirement: "collected_and_cleared",
    chargebackWindowDays: 90,
    holdbackPercent: 0.1,
    approvalRoute: ["accounting_lead", "owner"],
    glExpenseAccount: "6100 · Commission Expense",
    glPayableAccount: "2210 · Commission Payable",
    glReserveAccount: "2215 · Commission Holdback Reserve",
    glClawbackAccount: "2216 · Commission Clawback Receivable",
    entityAssignment: "CCA LLC",
    status: "active",
    currentVersion: 3,
    lastUpdatedAt: now,
    updatedBy: "Rose Delacroix",
    owner: "Rose Delacroix",
    legalReviewRequired: false,
    legalReviewStatus: "not_required",
    accountingReviewRequired: true,
    accountingReviewStatus: "cleared",
    active: true,
    plainLanguageSummary:
      "Pay 10% of collected and cleared CCA service revenue after excluding pass-through funds, refunds, credits, chargebacks, and noncommissionable items. When Tara qualifies at 5%, the salesperson receives the remaining portion of the standard 10% pool.",
  },
  {
    id: "cp_tara_relationship",
    name: "Tara — Brand Ambassador / Relationship (5%)",
    description: "Tara's stacked relationship-creator slot on eligible first-year CCA revenue.",
    family: "brand_ambassador_participation",
    disbursementClass:
      DEFAULT_FAMILY_DISBURSEMENT_CLASS.brand_ambassador_participation,
    basis: "collected_and_cleared_nrsr",
    defaultRate: 0.05,
    formulaText: "5% × (eligible first-year collected NRSR) — carved from standard 10% pool",
    effectiveDate: "2026-01-01",
    participantCount: 1,
    eligibleServices: ["Compliance Onboarding", "Advisory Retainer"],
    eligibleProducts: [],
    eligibleApps: ["CCA Suite"],
    eligibleDepartments: ["Partnerships"],
    eligibleChannels: ["Direct", "Strategic"],
    eligibleEntities: ["CCA LLC"],
    eligibleCustomerTypes: ["Standard"],
    geographicScope: ["US"],
    houseAccountRule: "suppress",
    survivalMonths: 12,
    passThroughTreatment: "excluded",
    collectionRequirement: "collected_and_cleared",
    chargebackWindowDays: 90,
    holdbackPercent: 0.1,
    approvalRoute: ["accounting_lead", "owner"],
    glExpenseAccount: "6120 · Ambassador Participation",
    glPayableAccount: "2220 · Ambassador Payable",
    glReserveAccount: "2225 · Ambassador Reserve",
    glClawbackAccount: "2226 · Ambassador Clawback",
    entityAssignment: "CCA LLC",
    status: "active",
    currentVersion: 2,
    lastUpdatedAt: now,
    updatedBy: "Rose Delacroix",
    owner: "Rose Delacroix",
    legalReviewRequired: true,
    legalReviewStatus: "cleared",
    accountingReviewRequired: true,
    accountingReviewStatus: "cleared",
    active: true,
    plainLanguageSummary:
      "Tara receives 5% of eligible first-year collected CCA revenue when she directly sourced, materially developed, or helped secure the client. Her 5% is carved out of the standard 10% pool — the salesperson receives the remaining 5%.",
  },
  {
    id: "cp_software",
    name: "Software Participation — Recurring NRSR",
    description: "Monthly participation on collected-and-cleared NRSR for covered software accounts.",
    family: "software_participation",
    disbursementClass: DEFAULT_FAMILY_DISBURSEMENT_CLASS.software_participation,
    basis: "collected_and_cleared_nrsr",
    defaultRate: 0.03,
    formulaText: "3% × monthly collected NRSR (covered software subscription lines)",
    effectiveDate: "2026-01-01",
    participantCount: 3,
    eligibleServices: [],
    eligibleProducts: ["Compliance Suite Pro"],
    eligibleApps: ["Compliance Suite"],
    eligibleDepartments: ["Sales", "Customer Success"],
    eligibleChannels: ["Direct"],
    eligibleEntities: ["CCA LLC"],
    eligibleCustomerTypes: ["Standard"],
    geographicScope: ["US"],
    houseAccountRule: "reduce",
    survivalMonths: 12,
    passThroughTreatment: "excluded",
    collectionRequirement: "collected_and_cleared",
    chargebackWindowDays: 90,
    holdbackPercent: 0.1,
    approvalRoute: ["accounting_lead", "owner"],
    glExpenseAccount: "6130 · Software Participation",
    glPayableAccount: "2230 · Software Participation Payable",
    glReserveAccount: "2235 · Software Reserve",
    glClawbackAccount: "2236 · Software Clawback",
    entityAssignment: "CCA LLC",
    status: "active",
    currentVersion: 1,
    lastUpdatedAt: now,
    updatedBy: "Rose Delacroix",
    owner: "Rose Delacroix",
    legalReviewRequired: false,
    legalReviewStatus: "not_required",
    accountingReviewRequired: true,
    accountingReviewStatus: "cleared",
    active: true,
    plainLanguageSummary:
      "3% of monthly collected & cleared software NRSR on covered subscription accounts, paid monthly with 12-month post-termination survival by default.",
  },
  {
    id: "cp_referral",
    name: "Referral Partner — 5% First Year",
    description: "External referral partners on year-one collected revenue only.",
    family: "referral",
    disbursementClass: DEFAULT_FAMILY_DISBURSEMENT_CLASS.referral,
    basis: "collected_realized_service_revenue",
    defaultRate: 0.05,
    formulaText: "5% × collected first-year service revenue (year 1 only)",
    effectiveDate: "2026-01-01",
    participantCount: 4,
    eligibleServices: ["Compliance Onboarding"],
    eligibleProducts: [],
    eligibleApps: [],
    eligibleDepartments: ["Partnerships"],
    eligibleChannels: ["Referral"],
    eligibleEntities: ["CCA LLC"],
    eligibleCustomerTypes: ["Standard"],
    geographicScope: ["US"],
    houseAccountRule: "suppress",
    survivalMonths: "none",
    passThroughTreatment: "excluded",
    collectionRequirement: "collected_and_cleared",
    chargebackWindowDays: 90,
    holdbackPercent: 0.15,
    approvalRoute: ["accounting_lead", "owner"],
    glExpenseAccount: "6110 · Referral Commission",
    glPayableAccount: "2211 · Referral Payable",
    glReserveAccount: "2212 · Referral Reserve",
    glClawbackAccount: "2213 · Referral Clawback",
    entityAssignment: "CCA LLC",
    status: "active",
    currentVersion: 1,
    lastUpdatedAt: now,
    updatedBy: "Rose Delacroix",
    owner: "Rose Delacroix",
    legalReviewRequired: false,
    legalReviewStatus: "not_required",
    accountingReviewRequired: true,
    accountingReviewStatus: "cleared",
    active: true,
    plainLanguageSummary:
      "Pay external referral partners 5% of collected first-year revenue. No post-termination survival.",
  },
  {
    id: "cp_milestone_bonus",
    name: "Milestone Bonus — Enterprise Onboarding",
    description: "One-time bonus when an enterprise onboarding milestone is verified.",
    family: "milestone_bonus",
    disbursementClass: DEFAULT_FAMILY_DISBURSEMENT_CLASS.milestone_bonus,
    basis: "milestone_amount",
    fixedAmount: 5000,
    formulaText: "$5,000 fixed per verified enterprise milestone",
    effectiveDate: "2026-04-01",
    participantCount: 6,
    eligibleServices: ["Compliance Onboarding"],
    eligibleProducts: [],
    eligibleApps: [],
    eligibleDepartments: ["Delivery"],
    eligibleChannels: ["Direct"],
    eligibleEntities: ["CCA LLC"],
    eligibleCustomerTypes: ["Enterprise"],
    geographicScope: ["US"],
    houseAccountRule: "reduce",
    survivalMonths: "none",
    passThroughTreatment: "excluded",
    collectionRequirement: "collected_and_cleared",
    chargebackWindowDays: 0,
    holdbackPercent: 0,
    approvalRoute: ["accounting_lead", "owner"],
    glExpenseAccount: "6300 · Bonus Expense",
    glPayableAccount: "2250 · Bonus Payable",
    glReserveAccount: "2255 · Bonus Reserve",
    glClawbackAccount: "2256 · Bonus Clawback",
    entityAssignment: "CCA LLC",
    status: "active",
    currentVersion: 1,
    lastUpdatedAt: now,
    updatedBy: "Rose Delacroix",
    owner: "Rose Delacroix",
    legalReviewRequired: false,
    legalReviewStatus: "not_required",
    accountingReviewRequired: true,
    accountingReviewStatus: "cleared",
    active: true,
    plainLanguageSummary:
      "Pay $5,000 to the delivery owner when an enterprise onboarding milestone is verified. Zero-day chargeback window; no holdback.",
  },
  {
    id: "cp_investor_review",
    name: "Investor Milestone — Pending Legal Review",
    description: "Investor-linked milestone comp. Requires legal + Owner approval before activation.",
    family: "investor_milestone_bonus",
    disbursementClass: DEFAULT_FAMILY_DISBURSEMENT_CLASS.investor_milestone_bonus,
    basis: "milestone_amount",
    fixedAmount: 25000,
    formulaText: "$25,000 per approved investor milestone",
    effectiveDate: "2026-09-01",
    participantCount: 2,
    eligibleServices: [],
    eligibleProducts: [],
    eligibleApps: [],
    eligibleDepartments: ["Executive"],
    eligibleChannels: [],
    eligibleEntities: ["CCA LLC"],
    eligibleCustomerTypes: [],
    geographicScope: ["US"],
    houseAccountRule: "suppress",
    survivalMonths: "none",
    passThroughTreatment: "excluded",
    collectionRequirement: "collected_and_cleared",
    chargebackWindowDays: 0,
    holdbackPercent: 0,
    approvalRoute: ["accounting_lead", "legal", "owner"],
    glExpenseAccount: "6400 · Investor Comp",
    glPayableAccount: "2260 · Investor Comp Payable",
    glReserveAccount: "2265 · Investor Reserve",
    glClawbackAccount: "2266 · Investor Clawback",
    entityAssignment: "CCA LLC",
    status: "requires_legal_review",
    currentVersion: 1,
    lastUpdatedAt: now,
    updatedBy: "Rose Delacroix",
    owner: "Rose Delacroix",
    legalReviewRequired: true,
    legalReviewStatus: "pending",
    accountingReviewRequired: true,
    accountingReviewStatus: "pending",
    active: false,
    plainLanguageSummary:
      "Investor-linked milestone bonus. Cannot activate without cleared legal review AND Owner approval.",
  },
  {
    id: "cp_house",
    name: "House Account — Suppressed",
    description: "House-account bucket. Pool suppressed to protect margin.",
    family: "house_account",
    disbursementClass: DEFAULT_FAMILY_DISBURSEMENT_CLASS.house_account,
    basis: "collected_realized_service_revenue",
    defaultRate: 0,
    formulaText: "0% — house-account rule suppresses pool",
    effectiveDate: "2026-01-01",
    participantCount: 0,
    eligibleServices: [],
    eligibleProducts: [],
    eligibleApps: [],
    eligibleDepartments: [],
    eligibleChannels: [],
    eligibleEntities: ["CCA LLC"],
    eligibleCustomerTypes: ["HouseAccount"],
    geographicScope: ["US"],
    houseAccountRule: "suppress",
    survivalMonths: "none",
    passThroughTreatment: "excluded",
    collectionRequirement: "collected_and_cleared",
    chargebackWindowDays: 0,
    holdbackPercent: 0,
    approvalRoute: ["owner"],
    glExpenseAccount: "—",
    glPayableAccount: "—",
    glReserveAccount: "—",
    glClawbackAccount: "—",
    entityAssignment: "CCA LLC",
    status: "active",
    currentVersion: 1,
    lastUpdatedAt: now,
    updatedBy: "Rose Delacroix",
    owner: "Rose Delacroix",
    legalReviewRequired: false,
    legalReviewStatus: "not_required",
    accountingReviewRequired: false,
    accountingReviewStatus: "not_required",
    active: true,
    plainLanguageSummary:
      "House accounts do not participate in sales pool by default. Pool is suppressed to protect margin.",
  },
  {
    id: "cp_retainer",
    name: "Executive Advisory Retainer — Draft",
    description: "Fixed monthly retainer to advisory partner. Draft.",
    family: "retainer",
    disbursementClass: DEFAULT_FAMILY_DISBURSEMENT_CLASS.retainer,
    basis: "fixed_amount",
    fixedAmount: 7500,
    formulaText: "$7,500 per month (retainer)",
    effectiveDate: "2026-08-01",
    participantCount: 1,
    eligibleServices: [],
    eligibleProducts: [],
    eligibleApps: [],
    eligibleDepartments: ["Executive"],
    eligibleChannels: [],
    eligibleEntities: ["CCA LLC"],
    eligibleCustomerTypes: [],
    geographicScope: ["US"],
    houseAccountRule: "suppress",
    survivalMonths: 3,
    passThroughTreatment: "excluded",
    collectionRequirement: "custom",
    chargebackWindowDays: 0,
    holdbackPercent: 0,
    approvalRoute: ["accounting_lead", "owner"],
    glExpenseAccount: "6500 · Advisory Retainer",
    glPayableAccount: "2270 · Retainer Payable",
    glReserveAccount: "—",
    glClawbackAccount: "—",
    entityAssignment: "CCA LLC",
    status: "draft",
    currentVersion: 1,
    lastUpdatedAt: now,
    updatedBy: "Rose Delacroix",
    owner: "Rose Delacroix",
    legalReviewRequired: true,
    legalReviewStatus: "pending",
    accountingReviewRequired: true,
    accountingReviewStatus: "pending",
    active: false,
    plainLanguageSummary:
      "Monthly retainer to a named advisory partner. Draft — pending legal + accounting review.",
  },
];

export const MOCK_PARTICIPANTS: CompensationParticipant[] = [
  {
    id: "pt_tara",
    name: "Tara Casella",
    type: "brand_ambassador",
    department: "Partnerships",
    defaultRole: "brand_ambassador",
    activePlans: 2,
    attributionCount: 14,
    payableBalance: 18250,
    holdbackBalance: 2025,
    clawbackExposure: 0,
    paymentMethod: "ap",
    taxDocumentStatus: "on_file",
    legalReviewStatus: "cleared",
    active: true,
    restrictions: ["Preexisting-pipeline conflicts require review"],
    survivalRights: "12 months post-termination on covered accounts",
    totalProjected: 42000,
    totalEarned: 30500,
    totalApproved: 22500,
    totalReserved: 2025,
    totalPayable: 18250,
    totalPaid: 12250,
    totalHeld: 0,
    totalClawback: 0,
  },
  {
    id: "pt_jamie",
    name: "Jamie Rivera",
    type: "salesperson",
    department: "Sales",
    defaultRole: "closer",
    activePlans: 2,
    attributionCount: 22,
    payableBalance: 14100,
    holdbackBalance: 1560,
    clawbackExposure: 320,
    paymentMethod: "payroll",
    taxDocumentStatus: "not_applicable",
    legalReviewStatus: "not_required",
    active: true,
    restrictions: [],
    totalProjected: 58000,
    totalEarned: 41200,
    totalApproved: 28900,
    totalReserved: 1560,
    totalPayable: 14100,
    totalPaid: 27100,
    totalHeld: 0,
    totalClawback: 320,
  },
  {
    id: "pt_priya",
    name: "Priya Kapoor",
    type: "salesperson",
    department: "Sales",
    defaultRole: "closer",
    activePlans: 1,
    attributionCount: 9,
    payableBalance: 6200,
    holdbackBalance: 690,
    clawbackExposure: 0,
    paymentMethod: "payroll",
    taxDocumentStatus: "not_applicable",
    legalReviewStatus: "not_required",
    active: true,
    restrictions: [],
    totalProjected: 21000,
    totalEarned: 14000,
    totalApproved: 8900,
    totalReserved: 690,
    totalPayable: 6200,
    totalPaid: 8000,
    totalHeld: 0,
    totalClawback: 0,
  },
  {
    id: "pt_northstar",
    name: "NorthStar Advisors",
    type: "referral_partner",
    department: "External",
    defaultRole: "referral_source",
    activePlans: 1,
    attributionCount: 5,
    payableBalance: 4400,
    holdbackBalance: 780,
    clawbackExposure: 0,
    paymentMethod: "ach",
    taxDocumentStatus: "on_file",
    legalReviewStatus: "cleared",
    active: true,
    restrictions: ["Year-one only"],
    totalProjected: 12000,
    totalEarned: 8600,
    totalApproved: 5200,
    totalReserved: 780,
    totalPayable: 4400,
    totalPaid: 3400,
    totalHeld: 0,
    totalClawback: 0,
  },
  {
    id: "pt_reliant",
    name: "Reliant Strategic",
    type: "strategic_partner",
    department: "External",
    defaultRole: "strategic_partner",
    activePlans: 1,
    attributionCount: 3,
    payableBalance: 2100,
    holdbackBalance: 300,
    clawbackExposure: 0,
    paymentMethod: "ach",
    taxDocumentStatus: "on_file",
    legalReviewStatus: "cleared",
    active: true,
    restrictions: ["Signed partner agreement required"],
    totalProjected: 8000,
    totalEarned: 5100,
    totalApproved: 2400,
    totalReserved: 300,
    totalPayable: 2100,
    totalPaid: 2700,
    totalHeld: 0,
    totalClawback: 0,
  },
  {
    id: "pt_devon",
    name: "Devon Locke",
    type: "salesperson",
    department: "Sales",
    defaultRole: "closer",
    activePlans: 1,
    attributionCount: 6,
    payableBalance: 3600,
    holdbackBalance: 400,
    clawbackExposure: 0,
    paymentMethod: "payroll",
    taxDocumentStatus: "not_applicable",
    legalReviewStatus: "not_required",
    active: true,
    restrictions: [],
    totalProjected: 15000,
    totalEarned: 9200,
    totalApproved: 4900,
    totalReserved: 400,
    totalPayable: 3600,
    totalPaid: 4600,
    totalHeld: 0,
    totalClawback: 0,
  },
  {
    id: "pt_teampool",
    name: "Delivery Team Pool",
    type: "team_pool",
    department: "Delivery",
    defaultRole: "team_pool",
    activePlans: 1,
    attributionCount: 4,
    payableBalance: 8000,
    holdbackBalance: 0,
    clawbackExposure: 0,
    paymentMethod: "payroll",
    taxDocumentStatus: "not_applicable",
    legalReviewStatus: "not_required",
    active: true,
    restrictions: ["Distribution requires Owner sign-off"],
    totalProjected: 20000,
    totalEarned: 14000,
    totalApproved: 12000,
    totalReserved: 0,
    totalPayable: 8000,
    totalPaid: 4000,
    totalHeld: 0,
    totalClawback: 0,
  },
  {
    id: "pt_investor",
    name: "Investor: Bright Harbor LP",
    type: "investor",
    department: "External",
    defaultRole: "investor",
    activePlans: 1,
    attributionCount: 0,
    payableBalance: 0,
    holdbackBalance: 0,
    clawbackExposure: 0,
    paymentMethod: "wire",
    taxDocumentStatus: "on_file",
    legalReviewStatus: "pending",
    active: false,
    restrictions: ["No auto-disbursement", "Requires legal + Owner approval"],
    totalProjected: 25000,
    totalEarned: 0,
    totalApproved: 0,
    totalReserved: 0,
    totalPayable: 0,
    totalPaid: 0,
    totalHeld: 0,
    totalClawback: 0,
  },
];

export const MOCK_PLAN_PARTICIPANTS: CompensationPlanParticipant[] = [
  { id: "pp_1", planId: "cp_std_sales", participantId: "pt_jamie", participantName: "Jamie Rivera", role: "closer", effectiveFrom: "2026-01-01", active: true },
  { id: "pp_2", planId: "cp_std_sales", participantId: "pt_priya", participantName: "Priya Kapoor", role: "closer", effectiveFrom: "2026-01-01", active: true },
  { id: "pp_3", planId: "cp_std_sales", participantId: "pt_devon", participantName: "Devon Locke", role: "closer", effectiveFrom: "2026-01-01", active: true },
  { id: "pp_4", planId: "cp_tara_relationship", participantId: "pt_tara", participantName: "Tara Casella", role: "brand_ambassador", effectiveFrom: "2026-01-01", overridePercent: 0.05, active: true },
  { id: "pp_5", planId: "cp_software", participantId: "pt_jamie", participantName: "Jamie Rivera", role: "account_manager", effectiveFrom: "2026-01-01", active: true },
  { id: "pp_6", planId: "cp_referral", participantId: "pt_northstar", participantName: "NorthStar Advisors", role: "referral_source", effectiveFrom: "2026-01-01", active: true },
  { id: "pp_7", planId: "cp_referral", participantId: "pt_reliant", participantName: "Reliant Strategic", role: "strategic_partner", effectiveFrom: "2026-01-01", active: true },
];

export const MOCK_ATTRIBUTIONS: CompensationAttribution[] = [
  {
    id: "ca_axiom",
    opportunityId: "opp_axiom",
    opportunityName: "Axiom Manufacturing — Compliance Onboarding",
    customerId: "cust_axiom",
    customerName: "Axiom Manufacturing",
    sourceSystem: "crm",
    relatedInvoiceId: "inv_ax_01",
    relatedPaymentId: "pay_ax_01",
    contributions: [
      {
        id: "co_ax_1",
        participantId: "pt_tara",
        participantName: "Tara Casella",
        role: "relationship_creator",
        poolId: "pool_ax_sales",
        poolName: "Sales Pool (10%)",
        splitPercent: 0.5,
        eligibility: "eligible",
        evidenceCount: 4,
        approvalStatus: "verified",
        effectiveDate: "2026-05-01",
      },
      {
        id: "co_ax_2",
        participantId: "pt_jamie",
        participantName: "Jamie Rivera",
        role: "closer",
        poolId: "pool_ax_sales",
        poolName: "Sales Pool (10%)",
        splitPercent: 0.5,
        eligibility: "eligible",
        evidenceCount: 2,
        approvalStatus: "verified",
        effectiveDate: "2026-05-01",
      },
    ],
    totalPools: [{ poolId: "pool_ax_sales", poolName: "Sales Pool (10%)", totalPercent: 1, valid: true }],
    overallStatus: "verified",
    createdAt: now,
    updatedAt: now,
    createdBy: "Rose Delacroix",
  },
  {
    id: "ca_helio",
    opportunityId: "opp_helio",
    opportunityName: "Helio Foods — Advisory Retainer",
    customerId: "cust_helio",
    customerName: "Helio Foods",
    sourceSystem: "crm",
    contributions: [
      {
        id: "co_he_1",
        participantId: "pt_priya",
        participantName: "Priya Kapoor",
        role: "closer",
        poolId: "pool_he_sales",
        poolName: "Sales Pool (10%)",
        splitPercent: 0.6,
        eligibility: "eligible",
        evidenceCount: 3,
        approvalStatus: "approved",
        effectiveDate: "2026-06-01",
      },
      {
        id: "co_he_2",
        participantId: "pt_northstar",
        participantName: "NorthStar Advisors",
        role: "referral_source",
        poolId: "pool_he_referral",
        poolName: "Referral Pool (5%)",
        splitPercent: 1,
        eligibility: "eligible",
        evidenceCount: 1,
        approvalStatus: "approved",
        effectiveDate: "2026-06-01",
      },
    ],
    totalPools: [
      { poolId: "pool_he_sales", poolName: "Sales Pool (10%)", totalPercent: 0.6, valid: false },
      { poolId: "pool_he_referral", poolName: "Referral Pool (5%)", totalPercent: 1, valid: true },
    ],
    overallStatus: "conflict",
    createdAt: now,
    updatedAt: now,
    createdBy: "Rose Delacroix",
  },
  {
    id: "ca_vireo",
    opportunityId: "opp_vireo",
    opportunityName: "Vireo Tech — Software Subscription",
    customerId: "cust_vireo",
    customerName: "Vireo Tech",
    sourceSystem: "subscription",
    contributions: [
      {
        id: "co_vi_1",
        participantId: "pt_tara",
        participantName: "Tara Casella",
        role: "brand_ambassador",
        poolId: "pool_vi_soft",
        poolName: "Software Participation (3%)",
        splitPercent: 1,
        eligibility: "software_participation_eligible",
        evidenceCount: 5,
        approvalStatus: "verified",
        effectiveDate: "2026-04-01",
      },
    ],
    totalPools: [
      { poolId: "pool_vi_soft", poolName: "Software Participation (3%)", totalPercent: 1, valid: true },
    ],
    overallStatus: "verified",
    createdAt: now,
    updatedAt: now,
    createdBy: "Rose Delacroix",
  },
  {
    id: "ca_lark",
    opportunityId: "opp_lark",
    opportunityName: "Lark Retail — Preexisting Pipeline",
    customerId: "cust_lark",
    customerName: "Lark Retail",
    sourceSystem: "crm",
    contributions: [
      {
        id: "co_la_1",
        participantId: "pt_tara",
        participantName: "Tara Casella",
        role: "relationship_creator",
        poolId: "pool_la_sales",
        poolName: "Sales Pool (10%)",
        splitPercent: 0.5,
        eligibility: "preexisting_pipeline_conflict",
        evidenceCount: 1,
        approvalStatus: "under_review",
        effectiveDate: "2026-06-15",
        conflictId: "conf_lark",
      },
      {
        id: "co_la_2",
        participantId: "pt_devon",
        participantName: "Devon Locke",
        role: "closer",
        poolId: "pool_la_sales",
        poolName: "Sales Pool (10%)",
        splitPercent: 0.5,
        eligibility: "needs_evidence",
        evidenceCount: 0,
        approvalStatus: "under_review",
        effectiveDate: "2026-06-15",
        conflictId: "conf_lark",
      },
    ],
    totalPools: [{ poolId: "pool_la_sales", poolName: "Sales Pool (10%)", totalPercent: 1, valid: true }],
    overallStatus: "conflict",
    createdAt: now,
    updatedAt: now,
    createdBy: "Rose Delacroix",
  },
];

export const MOCK_EVIDENCE: AttributionEvidence[] = [
  {
    id: "ev_1",
    attributionId: "ca_axiom",
    contributionId: "co_ax_1",
    type: "email",
    date: "2026-04-11",
    source: "tara@cca.example",
    uploadedBy: "Tara Casella",
    opportunityId: "opp_axiom",
    participantId: "pt_tara",
    relevance: "primary",
    confidence: 0.92,
    verified: true,
    notes: "Initial outreach email to Axiom CFO",
    createdAt: now,
  },
  {
    id: "ev_2",
    attributionId: "ca_axiom",
    contributionId: "co_ax_1",
    type: "calendar_event",
    date: "2026-04-16",
    source: "Google Calendar",
    uploadedBy: "Tara Casella",
    opportunityId: "opp_axiom",
    participantId: "pt_tara",
    relevance: "primary",
    confidence: 0.88,
    verified: true,
    createdAt: now,
  },
  {
    id: "ev_3",
    attributionId: "ca_axiom",
    contributionId: "co_ax_2",
    type: "meeting_note",
    date: "2026-05-02",
    source: "CRM",
    uploadedBy: "Jamie Rivera",
    opportunityId: "opp_axiom",
    participantId: "pt_jamie",
    relevance: "primary",
    confidence: 0.91,
    verified: true,
    createdAt: now,
  },
  {
    id: "ev_4",
    attributionId: "ca_lark",
    contributionId: "co_la_1",
    type: "leadership_confirmation",
    date: "2026-06-10",
    source: "Rose Delacroix",
    uploadedBy: "Rose Delacroix",
    opportunityId: "opp_lark",
    participantId: "pt_tara",
    relevance: "supporting",
    confidence: 0.55,
    verified: false,
    notes: "Rose noted Tara had prior conversations but Lark was in the pipeline pre-Tara",
    createdAt: now,
  },
  {
    id: "ev_5",
    attributionId: "ca_vireo",
    contributionId: "co_vi_1",
    type: "partner_agreement",
    date: "2026-03-20",
    source: "Signed PDF",
    uploadedBy: "Rose Delacroix",
    opportunityId: "opp_vireo",
    participantId: "pt_tara",
    relevance: "primary",
    confidence: 0.98,
    verified: true,
    createdAt: now,
  },
];

export const MOCK_CONFLICTS: AttributionConflict[] = [
  {
    id: "conf_lark",
    attributionId: "ca_lark",
    opportunityName: "Lark Retail — Preexisting Pipeline",
    type: "tara_preexisting_pipeline",
    participants: ["Tara Casella", "Devon Locke"],
    competingClaims:
      "Tara claims relationship-creator credit; Devon claims closer credit. Deal existed in pipeline before Tara's material involvement.",
    evidenceCount: 1,
    financialImpact: 8500,
    affectedPlans: ["Tara — Brand Ambassador (5%)", "Standard Sales Pool (10%)"],
    suggestedResolution: "Route to Rose for material-development determination; require signed leadership confirmation.",
    requiredApprover: "Owner (Rose)",
    status: "leadership_review",
    timeline: [
      { at: "2026-06-15T10:00:00Z", actor: "System", action: "Conflict detected — preexisting pipeline" },
      { at: "2026-06-15T14:00:00Z", actor: "Rose Delacroix", action: "Routed to leadership review" },
    ],
  },
  {
    id: "conf_helio",
    attributionId: "ca_helio",
    opportunityName: "Helio Foods — Split does not equal 100%",
    type: "split_not_100",
    participants: ["Priya Kapoor"],
    competingClaims: "Sales pool split totals 60% — 40% unattributed.",
    evidenceCount: 3,
    financialImpact: 2400,
    affectedPlans: ["Standard Sales Pool (10%)"],
    suggestedResolution: "Add relationship-creator contribution or increase Priya's split to 100%.",
    requiredApprover: "Accounting Lead",
    status: "accounting_review",
    timeline: [
      { at: "2026-06-01T09:30:00Z", actor: "System", action: "Split validation failed" },
    ],
  },
];

export const MOCK_PLAN_VERSIONS: CompensationPlanVersion[] = [
  {
    id: "cpv_std_v3",
    planId: "cp_std_sales",
    version: 3,
    effectiveDate: "2026-06-01",
    createdBy: "Rose Delacroix",
    createdAt: now,
    changeSummary: "Chargeback window extended from 60 → 90 days; holdback raised to 10%.",
    priorVersion: 2,
    approvalStatus: "approved",
    activeFrom: "2026-06-01",
    impactedCalculations: 47,
    resolvedPolicySnapshot: resolveCompensationPolicy(),
    planSnapshot: MOCK_PLANS[0],
  },
  {
    id: "cpv_std_v2",
    planId: "cp_std_sales",
    version: 2,
    effectiveDate: "2026-03-01",
    createdBy: "Rose Delacroix",
    createdAt: "2026-03-01T00:00:00Z",
    changeSummary: "Tara relationship carve-out documented in plain-language summary.",
    priorVersion: 1,
    approvalStatus: "retired",
    activeFrom: "2026-03-01",
    activeTo: "2026-05-31",
    impactedCalculations: 88,
    resolvedPolicySnapshot: resolveCompensationPolicy(),
    planSnapshot: MOCK_PLANS[0],
  },
  {
    id: "cpv_std_v1",
    planId: "cp_std_sales",
    version: 1,
    effectiveDate: "2026-01-01",
    createdBy: "Rose Delacroix",
    createdAt: "2026-01-01T00:00:00Z",
    changeSummary: "Initial plan.",
    approvalStatus: "retired",
    activeFrom: "2026-01-01",
    activeTo: "2026-02-28",
    impactedCalculations: 62,
    resolvedPolicySnapshot: resolveCompensationPolicy(),
    planSnapshot: MOCK_PLANS[0],
  },
];
