/**
 * 6B-3 operations mock data — demonstration only, fictional records.
 */

import type { ID } from "../../types";
import { resolveCompensationPolicy } from "./policy-defaults";
import type {
  CompensationAdjustment,
  CompensationApproval,
  CompensationCalculation,
  CompensationCalculationLine,
  CompensationClawback,
  CompensationDispute,
  CompensationHoldback,
  CompensationPayable,
  CompensationPaymentBatch,
  CompensationReconciliation,
  CompensationReserve,
  CompensationReversal,
  CompensationStatement,
  CompensationVerification,
} from "./operations-types";

const now = "2026-07-13T14:00:00Z";

const basePolicy = resolveCompensationPolicy();

const snapshot = (planId: ID, version = 3) => ({
  planId,
  planVersion: version,
  resolvedPolicy: basePolicy,
  invariants: {
    passThroughExcluded: true,
    collectedRevenueRequired: true,
    stackingEnforced: true,
    noDoubleDip: true,
  },
});

// ─── Calculations ─────────────────────────────────────────────────────────

const line = (over: Partial<CompensationCalculationLine>): CompensationCalculationLine => ({
  id: `cl_${Math.random().toString(36).slice(2, 8)}`,
  participantId: "pp_jamie",
  participantName: "Jamie Rivera",
  compensationClass: "commission",
  planId: "cp_std_sales",
  planName: "Standard Sales Pool — 10%",
  planVersion: 3,
  poolId: "pool_sales",
  poolName: "Sales Pool (10%)",
  basis: "collected_and_cleared_nrsr",
  baseAmount: 10800,
  rate: 0.1,
  formulaText: "10% × realized revenue",
  grossAmount: 1080,
  exclusions: 0,
  holdback: 108,
  adjustment: 0,
  netPayable: 972,
  status: "approved",
  payDestination: "ADP Payroll",
  glExpenseAccount: "6100 · Commission Expense",
  glPayableAccount: "2210 · Commission Payable",
  explanation: "10% of $10,800 realized revenue = $1,080; 10% holdback applied.",
  reviewFlags: [],
  ...over,
});

export const MOCK_CALCULATIONS: CompensationCalculation[] = [
  {
    id: "calc_001",
    version: 1,
    participantId: "pp_jamie",
    participantName: "Jamie Rivera",
    opportunityId: "opp_5501",
    opportunityName: "Meridian Compliance Onboarding",
    customerId: "cust_meridian",
    customerName: "Meridian Advisors",
    planId: "cp_std_sales",
    planName: "Standard Sales Pool — 10%",
    planVersion: 3,
    compensationClasses: ["commission", "commission"],
    source: {
      type: "payment",
      id: "pay_9911",
      label: "Payment #9911 — Meridian Advisors",
      amount: 12000,
      date: "2026-07-05",
      collectionStatus: "cleared",
      clearanceDate: "2026-07-08",
      passThroughAmount: 1200,
      refunds: 0,
      credits: 0,
      chargebacks: 0,
      noncommissionable: 0,
    },
    grossPayment: 12000,
    passThroughExcluded: 1200,
    realizedRevenue: 10800,
    totalGross: 1080,
    totalHoldback: 108,
    totalAdjustment: 0,
    totalNetPayable: 972,
    lines: [
      line({
        id: "cl_001a",
        participantId: "pp_tara",
        participantName: "Tara Casella",
        compensationClass: "commission",
        planId: "cp_tara_relationship",
        planName: "Tara — Brand Ambassador (5%)",
        poolName: "Sales Pool (10%) — Ambassador slot",
        rate: 0.05,
        grossAmount: 540,
        holdback: 54,
        netPayable: 486,
        payDestination: "Accounts Payable",
        glExpenseAccount: "6120 · Ambassador Participation",
        glPayableAccount: "2220 · Ambassador Payable",
        explanation: "Tara qualifies at 5% (carved from 10% sales pool).",
      }),
      line({
        id: "cl_001b",
        rate: 0.05,
        grossAmount: 540,
        holdback: 54,
        netPayable: 486,
        explanation: "Salesperson receives remaining 5% of standard 10% sales pool.",
      }),
    ],
    marginImpact: -0.1,
    cashImpact: -972,
    status: "approved",
    approvalRoute: ["accounting_lead", "owner"],
    policySnapshot: snapshot("cp_std_sales"),
    riskFlags: [],
    legalReviewRequired: false,
    legalReviewStatus: "not_required",
    accountingReviewRequired: true,
    accountingReviewStatus: "cleared",
    createdAt: now,
    createdBy: "Rose Delacroix",
    updatedAt: now,
    expectedPayableDate: "2026-07-20",
    explanation:
      "Meridian Advisors paid $12,000 with $1,200 in pass-through fees, leaving $10,800 realized. Tara qualifies at 5% (carved) and salesperson receives the remaining 5%. Total compensation: $1,080; 10% holdback ($108) applied.",
    auditTimeline: [
      { at: now, actor: "Rose Delacroix", action: "Calculation created" },
      {
        at: now,
        actor: "Accounting Lead",
        action: "Verified attribution and pass-through exclusion",
      },
      { at: now, actor: "Rose Delacroix", action: "Approved" },
    ],
    sourceIdempotencyKey: "pay_9911:cp_std_sales:v3",
  },
  {
    id: "calc_002",
    version: 1,
    participantId: "pp_devon",
    participantName: "Devon Locke",
    opportunityName: "Northshore Advisory Retainer",
    customerName: "Northshore Financial",
    planId: "cp_std_sales",
    planName: "Standard Sales Pool — 10%",
    planVersion: 3,
    compensationClasses: ["commission"],
    source: {
      type: "invoice",
      id: "inv_4402",
      label: "Invoice #4402 — Northshore",
      amount: 8000,
      date: "2026-07-10",
      collectionStatus: "partially_collected",
      passThroughAmount: 500,
      refunds: 0,
      credits: 0,
      chargebacks: 0,
      noncommissionable: 0,
    },
    grossPayment: 4000,
    passThroughExcluded: 250,
    realizedRevenue: 3750,
    totalGross: 375,
    totalHoldback: 37.5,
    totalAdjustment: 0,
    totalNetPayable: 337.5,
    lines: [
      line({
        id: "cl_002a",
        participantName: "Devon Locke",
        participantId: "pp_devon",
        baseAmount: 3750,
        grossAmount: 375,
        holdback: 37.5,
        netPayable: 337.5,
        status: "pending_clearance",
      }),
    ],
    marginImpact: -0.1,
    cashImpact: -337.5,
    status: "pending_clearance",
    approvalRoute: ["accounting_lead"],
    policySnapshot: snapshot("cp_std_sales"),
    riskFlags: ["Partial payment — proportionate eligibility"],
    legalReviewRequired: false,
    legalReviewStatus: "not_required",
    accountingReviewRequired: true,
    accountingReviewStatus: "pending",
    createdAt: now,
    createdBy: "Rose Delacroix",
    updatedAt: now,
    explanation:
      "Partial payment of $4,000 of $8,000 invoiced. Pro-rata: $250 pass-through excluded → $3,750 realized → $375 compensation.",
    auditTimeline: [
      { at: now, actor: "Integration Service", action: "Draft created from partial payment event" },
    ],
    sourceIdempotencyKey: "inv_4402:cp_std_sales:v3",
  },
  {
    id: "calc_003",
    version: 1,
    participantId: "pp_tara",
    participantName: "Tara Casella",
    opportunityName: "Compliance Suite Pro — Monthly NRSR",
    customerName: "Ridgefield Wealth",
    planId: "cp_software",
    planName: "Software Participation — 3%",
    planVersion: 1,
    compensationClasses: ["commission"],
    source: {
      type: "subscription",
      id: "sub_2211",
      label: "Ridgefield Wealth · Compliance Suite Pro",
      amount: 2500,
      date: "2026-07-01",
      collectionStatus: "cleared",
      clearanceDate: "2026-07-04",
      passThroughAmount: 0,
      refunds: 0,
      credits: 0,
      chargebacks: 0,
      noncommissionable: 0,
    },
    grossPayment: 2500,
    passThroughExcluded: 0,
    realizedRevenue: 2500,
    totalGross: 75,
    totalHoldback: 7.5,
    totalAdjustment: 0,
    totalNetPayable: 67.5,
    lines: [
      line({
        id: "cl_003a",
        participantId: "pp_tara",
        participantName: "Tara Casella",
        compensationClass: "commission",
        planId: "cp_software",
        planName: "Software Participation — 3%",
        poolId: "pool_soft",
        poolName: "Software Participation (3%)",
        baseAmount: 2500,
        rate: 0.03,
        grossAmount: 75,
        holdback: 7.5,
        netPayable: 67.5,
        payDestination: "Accounts Payable",
        glExpenseAccount: "6130 · Software Participation",
        glPayableAccount: "2230 · Software Participation Payable",
        explanation: "3% of $2,500 monthly NRSR = $75.",
      }),
    ],
    marginImpact: -0.03,
    cashImpact: -67.5,
    status: "reserved",
    approvalRoute: ["accounting_lead"],
    policySnapshot: snapshot("cp_software", 1),
    riskFlags: [],
    legalReviewRequired: false,
    legalReviewStatus: "not_required",
    accountingReviewRequired: true,
    accountingReviewStatus: "cleared",
    createdAt: now,
    createdBy: "Rose Delacroix",
    updatedAt: now,
    expectedPayableDate: "2026-08-01",
    explanation: "Monthly software NRSR of $2,500; Tara's 3% participation = $75; 10% holdback.",
    auditTimeline: [
      { at: now, actor: "Rose Delacroix", action: "Calculation created" },
      { at: now, actor: "Rose Delacroix", action: "Reserved for August disbursement" },
    ],
    sourceIdempotencyKey: "sub_2211:2026-07:cp_software:v1",
  },
  {
    id: "calc_004",
    version: 1,
    participantId: "pp_kestrel",
    participantName: "Kestrel Media (Affiliate)",
    opportunityName: "Affiliate referral — Q3",
    customerName: "Various",
    planId: "cp_affiliate",
    planName: "Affiliate Pool — 5%",
    planVersion: 1,
    compensationClasses: ["affiliate_fee"],
    source: {
      type: "payment",
      id: "pay_9922",
      label: "Q3 affiliate revenue batch",
      amount: 6000,
      date: "2026-07-11",
      collectionStatus: "cleared",
      clearanceDate: "2026-07-13",
      passThroughAmount: 400,
      refunds: 0,
      credits: 0,
      chargebacks: 0,
      noncommissionable: 0,
    },
    grossPayment: 6000,
    passThroughExcluded: 400,
    realizedRevenue: 5600,
    totalGross: 280,
    totalHoldback: 42,
    totalAdjustment: 0,
    totalNetPayable: 238,
    lines: [
      line({
        id: "cl_004a",
        participantId: "pp_kestrel",
        participantName: "Kestrel Media",
        compensationClass: "affiliate_fee",
        planId: "cp_affiliate",
        planName: "Affiliate Pool — 5%",
        poolId: "pool_affiliate",
        poolName: "Affiliate Pool (5%)",
        baseAmount: 5600,
        rate: 0.05,
        grossAmount: 280,
        holdback: 42,
        netPayable: 238,
        payDestination: "Accounts Payable",
        glExpenseAccount: "6115 · Affiliate Fees",
        glPayableAccount: "2214 · Affiliate Payable",
        explanation: "5% of $5,600 realized affiliate-sourced revenue.",
      }),
    ],
    marginImpact: -0.05,
    cashImpact: -238,
    status: "payable",
    approvalRoute: ["accounting_lead"],
    policySnapshot: snapshot("cp_affiliate", 1),
    riskFlags: [],
    legalReviewRequired: false,
    legalReviewStatus: "not_required",
    accountingReviewRequired: true,
    accountingReviewStatus: "cleared",
    createdAt: now,
    createdBy: "Rose Delacroix",
    updatedAt: now,
    expectedPayableDate: "2026-07-20",
    explanation: "Affiliate fee — 5% of $5,600 realized = $280; 15% holdback applied.",
    auditTimeline: [{ at: now, actor: "Rose Delacroix", action: "Approved for AP disbursement" }],
    sourceIdempotencyKey: "pay_9922:cp_affiliate:v1",
  },
  {
    id: "calc_005",
    version: 1,
    participantId: "pp_priya",
    participantName: "Priya Kapoor",
    opportunityName: "Meridian Expansion",
    customerName: "Meridian Advisors",
    planId: "cp_std_sales",
    planName: "Standard Sales Pool — 10%",
    planVersion: 3,
    compensationClasses: ["commission"],
    source: {
      type: "payment",
      id: "pay_9933",
      label: "Meridian expansion payment",
      amount: 6000,
      date: "2026-07-09",
      collectionStatus: "cleared",
      clearanceDate: "2026-07-12",
      passThroughAmount: 200,
      refunds: 1500,
      credits: 0,
      chargebacks: 0,
      noncommissionable: 0,
    },
    grossPayment: 6000,
    passThroughExcluded: 200,
    realizedRevenue: 4300,
    totalGross: 430,
    totalHoldback: 43,
    totalAdjustment: -150,
    totalNetPayable: 237,
    lines: [
      line({
        id: "cl_005a",
        participantName: "Priya Kapoor",
        participantId: "pp_priya",
        baseAmount: 4300,
        grossAmount: 430,
        holdback: 43,
        adjustment: -150,
        netPayable: 237,
        status: "adjusted",
      }),
    ],
    marginImpact: -0.07,
    cashImpact: -237,
    status: "adjusted",
    approvalRoute: ["accounting_lead", "owner"],
    policySnapshot: snapshot("cp_std_sales"),
    riskFlags: ["Refund applied — recomputed pro-rata", "Below-target margin"],
    legalReviewRequired: false,
    legalReviewStatus: "not_required",
    accountingReviewRequired: true,
    accountingReviewStatus: "cleared",
    createdAt: now,
    createdBy: "Rose Delacroix",
    updatedAt: now,
    explanation:
      "Expansion payment $6,000; $1,500 refund reduced realized to $4,300; 10% pool = $430; refund adjustment −$150; net payable $237.",
    auditTimeline: [
      { at: now, actor: "Rose Delacroix", action: "Original calculation posted" },
      { at: now, actor: "Rose Delacroix", action: "Refund adjustment posted" },
    ],
    sourceIdempotencyKey: "pay_9933:cp_std_sales:v3",
  },
];

// ─── Verifications ────────────────────────────────────────────────────────

export const MOCK_VERIFICATIONS: CompensationVerification[] = [
  {
    id: "ver_001",
    calculationId: "calc_001",
    category: "attribution",
    status: "verified",
    reviewer: "Accounting Lead",
    reviewedAt: now,
    evidenceCount: 3,
  },
  {
    id: "ver_002",
    calculationId: "calc_001",
    category: "pass_through",
    status: "verified",
    reviewer: "Accounting Lead",
    reviewedAt: now,
    evidenceCount: 1,
  },
  {
    id: "ver_003",
    calculationId: "calc_002",
    category: "collection_clearance",
    status: "pending",
    evidenceCount: 0,
    note: "Awaiting payment clearance",
  },
  {
    id: "ver_004",
    calculationId: "calc_002",
    category: "split_validation",
    status: "pending",
    evidenceCount: 0,
  },
  {
    id: "ver_005",
    calculationId: "calc_005",
    category: "refund_chargeback",
    status: "evidence_requested",
    reviewer: "Rose Delacroix",
    note: "Need refund memo attached",
    evidenceCount: 1,
  },
  {
    id: "ver_006",
    calculationId: "calc_003",
    category: "software_participation",
    status: "verified",
    reviewer: "Accounting Lead",
    reviewedAt: now,
    evidenceCount: 2,
  },
];

// ─── Approvals ────────────────────────────────────────────────────────────

export const MOCK_APPROVALS: CompensationApproval[] = [
  {
    id: "app_001",
    calculationId: "calc_004",
    participantName: "Kestrel Media",
    amount: 238,
    planName: "Affiliate Pool — 5%",
    compensationClass: "affiliate_fee",
    marginImpact: -0.05,
    cashImpact: -238,
    reserveImpact: 42,
    requiredApproval: "accounting",
    deadline: "2026-07-18",
    recommendation: "Approve — evidence complete and margin within target.",
    status: "awaiting",
    riskFlags: [],
  },
  {
    id: "app_002",
    calculationId: "calc_005",
    participantName: "Priya Kapoor",
    amount: 237,
    planName: "Standard Sales Pool — 10%",
    compensationClass: "commission",
    marginImpact: -0.07,
    cashImpact: -237,
    reserveImpact: 43,
    requiredApproval: "owner",
    deadline: "2026-07-16",
    recommendation: "Approve with conditions — below-target margin flagged.",
    status: "awaiting",
    riskFlags: ["Below-target margin", "Refund adjustment applied"],
  },
  {
    id: "app_003",
    calculationId: "calc_001",
    participantName: "Tara Casella + Jamie Rivera",
    amount: 972,
    planName: "Standard + Ambassador (stacked)",
    compensationClass: "commission",
    marginImpact: -0.1,
    cashImpact: -972,
    reserveImpact: 108,
    requiredApproval: "owner",
    recommendation: "Approved by Owner",
    status: "approved",
    approver: "Rose Delacroix",
    approvedAt: now,
    riskFlags: [],
  },
];

// ─── Reserves ─────────────────────────────────────────────────────────────

export const MOCK_RESERVES: CompensationReserve[] = [
  {
    id: "res_001",
    participantId: "pp_tara",
    participantName: "Tara Casella",
    planId: "cp_tara_relationship",
    planName: "Tara — Brand Ambassador",
    compensationClass: "commission",
    approvedNotPayable: 486,
    reserved: 54,
    holdbacks: 54,
    drawOffset: 0,
    disputed: 0,
    chargebackExposure: 108,
    payableWithin7Days: 486,
    payableWithin30Days: 486,
    expectedPayableDate: "2026-07-20",
    destination: "ap",
  },
  {
    id: "res_002",
    participantId: "pp_jamie",
    participantName: "Jamie Rivera",
    planId: "cp_std_sales",
    planName: "Standard Sales Pool",
    compensationClass: "commission",
    approvedNotPayable: 486,
    reserved: 54,
    holdbacks: 54,
    drawOffset: 0,
    disputed: 0,
    chargebackExposure: 108,
    payableWithin7Days: 486,
    payableWithin30Days: 486,
    expectedPayableDate: "2026-07-20",
    destination: "payroll",
  },
  {
    id: "res_003",
    participantId: "pp_kestrel",
    participantName: "Kestrel Media",
    planId: "cp_affiliate",
    planName: "Affiliate Pool",
    compensationClass: "affiliate_fee",
    approvedNotPayable: 238,
    reserved: 42,
    holdbacks: 42,
    drawOffset: 0,
    disputed: 0,
    chargebackExposure: 42,
    payableWithin7Days: 238,
    payableWithin30Days: 238,
    expectedPayableDate: "2026-07-20",
    destination: "ap",
  },
];

// ─── Payables ─────────────────────────────────────────────────────────────

export const MOCK_PAYABLES: CompensationPayable[] = [
  {
    id: "pay_001",
    participantId: "pp_jamie",
    participantName: "Jamie Rivera",
    participantType: "salesperson",
    compensationClasses: ["commission"],
    periodStart: "2026-07-01",
    periodEnd: "2026-07-15",
    grossAmount: 540,
    adjustments: 0,
    holdbacks: 54,
    drawOffset: 0,
    clawbackOffset: 0,
    netPayable: 486,
    destination: "adp_payroll",
    scheduledDate: "2026-07-20",
    status: "ready_for_payroll",
    approver: "Rose Delacroix",
    approvedAt: now,
    calculationIds: ["calc_001"],
    glExpenseAccount: "6100 · Commission Expense",
    glPayableAccount: "2210 · Commission Payable",
    auditTimeline: [{ at: now, actor: "Rose Delacroix", action: "Approved for payroll export" }],
  },
  {
    id: "pay_002",
    participantId: "pp_tara",
    participantName: "Tara Casella",
    participantType: "brand_ambassador",
    compensationClasses: ["commission"],
    periodStart: "2026-07-01",
    periodEnd: "2026-07-15",
    grossAmount: 540,
    adjustments: 0,
    holdbacks: 54,
    drawOffset: 0,
    clawbackOffset: 0,
    netPayable: 486,
    destination: "accounts_payable",
    scheduledDate: "2026-07-20",
    status: "ready_for_ap",
    approver: "Rose Delacroix",
    approvedAt: now,
    calculationIds: ["calc_001"],
    glExpenseAccount: "6120 · Ambassador Participation",
    glPayableAccount: "2220 · Ambassador Payable",
    auditTimeline: [{ at: now, actor: "Rose Delacroix", action: "Approved for AP disbursement" }],
  },
  {
    id: "pay_003",
    participantId: "pp_kestrel",
    participantName: "Kestrel Media",
    participantType: "affiliate",
    compensationClasses: ["affiliate_fee"],
    periodStart: "2026-07-01",
    periodEnd: "2026-07-15",
    grossAmount: 280,
    adjustments: 0,
    holdbacks: 42,
    drawOffset: 0,
    clawbackOffset: 0,
    netPayable: 238,
    destination: "accounts_payable",
    scheduledDate: "2026-07-22",
    status: "scheduled",
    approver: "Accounting Lead",
    approvedAt: now,
    batchId: "batch_002",
    calculationIds: ["calc_004"],
    glExpenseAccount: "6115 · Affiliate Fees",
    glPayableAccount: "2214 · Affiliate Payable",
    auditTimeline: [{ at: now, actor: "Accounting Lead", action: "Scheduled in AP batch #002" }],
  },
];

// ─── Payment batches ──────────────────────────────────────────────────────

export const MOCK_BATCHES: CompensationPaymentBatch[] = [
  {
    id: "batch_001",
    destination: "adp_payroll",
    periodStart: "2026-07-01",
    periodEnd: "2026-07-15",
    participantCount: 3,
    grossAmount: 1620,
    adjustments: 0,
    netAmount: 1458,
    status: "export_ready",
    preparedBy: "Accounting Lead",
    preparedAt: now,
    approvedBy: "Rose Delacroix",
    approvedAt: now,
    scheduledDate: "2026-07-20",
    reconciliationState: "pending",
    payableIds: ["pay_001"],
    auditTimeline: [
      { at: now, actor: "Accounting Lead", action: "Batch drafted" },
      { at: now, actor: "Rose Delacroix", action: "Batch approved" },
    ],
  },
  {
    id: "batch_002",
    destination: "accounts_payable",
    periodStart: "2026-07-01",
    periodEnd: "2026-07-15",
    participantCount: 5,
    grossAmount: 2340,
    adjustments: 0,
    netAmount: 2106,
    status: "reviewed",
    preparedBy: "Accounting Lead",
    preparedAt: now,
    scheduledDate: "2026-07-22",
    reconciliationState: "pending",
    payableIds: ["pay_002", "pay_003"],
    auditTimeline: [{ at: now, actor: "Accounting Lead", action: "Batch drafted for AP" }],
  },
];

// ─── Statements ───────────────────────────────────────────────────────────

const s = (over: Partial<CompensationStatement>): CompensationStatement => ({
  id: `stmt_${Math.random().toString(36).slice(2, 8)}`,
  participantId: "pp_tara",
  participantName: "Tara Casella",
  participantType: "brand_ambassador",
  periodType: "monthly",
  periodStart: "2026-07-01",
  periodEnd: "2026-07-31",
  statementKind: "combined",
  beginningBalance: 0,
  projected: 0,
  earned: 0,
  verified: 0,
  approved: 0,
  reserved: 0,
  payable: 0,
  paid: 0,
  holdbacks: 0,
  adjustments: 0,
  clawbacks: 0,
  endingBalance: 0,
  sections: [],
  generatedAt: now,
  ...over,
});

export const MOCK_STATEMENTS: CompensationStatement[] = [
  s({
    id: "stmt_tara_jul",
    participantName: "Tara Casella",
    statementKind: "combined",
    beginningBalance: 0,
    projected: 720,
    earned: 615,
    verified: 615,
    approved: 615,
    reserved: 108,
    payable: 486,
    paid: 0,
    holdbacks: 108,
    adjustments: 0,
    clawbacks: 0,
    endingBalance: 615,
    sections: [
      { kind: "retainer", label: "Monthly retainer", total: 0, lines: [] },
      {
        kind: "brand_ambassador",
        label: "Brand ambassador — first-year 5%",
        total: 540,
        lines: [
          {
            id: "sl_1",
            compensationClass: "commission",
            planName: "Tara — Brand Ambassador (5%)",
            planVersion: 2,
            clientName: "Meridian Advisors",
            opportunityName: "Meridian Compliance Onboarding",
            amount: 540,
            status: "approved",
            effectiveDate: "2026-07-08",
            explanation: "5% carved slot on $10,800 realized revenue.",
          },
        ],
      },
      {
        kind: "software_participation",
        label: "Software participation — 3% NRSR",
        total: 75,
        lines: [
          {
            id: "sl_2",
            compensationClass: "commission",
            planName: "Software Participation — 3%",
            planVersion: 1,
            clientName: "Ridgefield Wealth",
            amount: 75,
            status: "reserved",
            effectiveDate: "2026-07-04",
            explanation: "3% of $2,500 monthly NRSR.",
          },
        ],
      },
      { kind: "event_stipend", label: "Event stipend", total: 0, lines: [] },
      { kind: "bonus", label: "Milestone bonus", total: 0, lines: [] },
    ],
  }),
  s({
    id: "stmt_jamie_jul",
    participantId: "pp_jamie",
    participantName: "Jamie Rivera",
    participantType: "salesperson",
    statementKind: "sales_commission",
    projected: 540,
    earned: 540,
    verified: 540,
    approved: 540,
    reserved: 54,
    payable: 486,
    holdbacks: 54,
    endingBalance: 540,
    sections: [
      {
        kind: "sales_commission",
        label: "Standard sales commission",
        total: 540,
        lines: [
          {
            id: "sl_j1",
            compensationClass: "commission",
            planName: "Standard Sales Pool — 10%",
            planVersion: 3,
            clientName: "Meridian Advisors",
            amount: 540,
            status: "approved",
            effectiveDate: "2026-07-08",
            explanation: "5% remainder of 10% pool after Tara carve.",
          },
        ],
      },
    ],
  }),
];

// ─── Holdbacks ────────────────────────────────────────────────────────────

export const MOCK_HOLDBACKS: CompensationHoldback[] = [
  {
    id: "hb_001",
    participantId: "pp_jamie",
    participantName: "Jamie Rivera",
    calculationId: "calc_001",
    planId: "cp_std_sales",
    planName: "Standard Sales Pool",
    originalCompensation: 540,
    holdbackPercent: 0.1,
    holdbackAmount: 54,
    holdStart: "2026-07-08",
    chargebackWindowEnd: "2026-10-06",
    riskStatus: "low",
    riskTriggers: [],
    releaseMethod: "automatic",
    releasedAmount: 0,
    remainingAmount: 54,
    status: "held",
    auditTimeline: [{ at: now, actor: "System", action: "Holdback created (10%)" }],
  },
  {
    id: "hb_002",
    participantId: "pp_tara",
    participantName: "Tara Casella",
    calculationId: "calc_001",
    planId: "cp_tara_relationship",
    planName: "Tara — Brand Ambassador",
    originalCompensation: 540,
    holdbackPercent: 0.1,
    holdbackAmount: 54,
    holdStart: "2026-07-08",
    chargebackWindowEnd: "2026-10-06",
    riskStatus: "low",
    riskTriggers: [],
    releaseMethod: "automatic",
    releasedAmount: 0,
    remainingAmount: 54,
    status: "held",
    auditTimeline: [{ at: now, actor: "System", action: "Holdback created (10%)" }],
  },
  {
    id: "hb_003",
    participantId: "pp_kestrel",
    participantName: "Kestrel Media",
    calculationId: "calc_004",
    planId: "cp_affiliate",
    planName: "Affiliate Pool",
    originalCompensation: 280,
    holdbackPercent: 0.15,
    holdbackAmount: 42,
    holdStart: "2026-07-13",
    chargebackWindowEnd: "2026-10-11",
    riskStatus: "medium",
    riskTriggers: ["Missing evidence", "Large affiliate batch"],
    releaseMethod: "rose_approval",
    requiredApproval: "Owner",
    releasedAmount: 0,
    remainingAmount: 42,
    status: "held",
    auditTimeline: [{ at: now, actor: "System", action: "Holdback created (15%)" }],
  },
  {
    id: "hb_004",
    participantId: "pp_devon",
    participantName: "Devon Locke",
    calculationId: "calc_prev_007",
    planId: "cp_std_sales",
    planName: "Standard Sales Pool",
    originalCompensation: 900,
    holdbackPercent: 0.1,
    holdbackAmount: 90,
    holdStart: "2026-04-01",
    chargebackWindowEnd: "2026-06-30",
    riskStatus: "low",
    riskTriggers: [],
    releaseMethod: "automatic",
    releasedAmount: 0,
    remainingAmount: 90,
    status: "eligible_for_release",
    auditTimeline: [
      { at: "2026-04-01T14:00:00Z", actor: "System", action: "Holdback created" },
      { at: now, actor: "System", action: "Chargeback window expired — eligible for release" },
    ],
  },
];

// ─── Adjustments / reversals ─────────────────────────────────────────────

export const MOCK_ADJUSTMENTS: CompensationAdjustment[] = [
  {
    id: "adj_001",
    originalCalculationId: "calc_005",
    participantId: "pp_priya",
    participantName: "Priya Kapoor",
    type: "refund",
    amount: -150,
    reason: "$1,500 refund on Meridian expansion payment",
    supportingRecord: "refund_2001",
    requestedBy: "Accounting Lead",
    requestedAt: now,
    requiredApprover: "Owner",
    effectivePeriod: "2026-07-31",
    status: "approved",
    accountingPreview: "DR Commission Expense $150 (reversal) / CR Commission Payable $150",
    auditTimeline: [
      { at: now, actor: "Accounting Lead", action: "Adjustment requested" },
      { at: now, actor: "Rose Delacroix", action: "Approved" },
    ],
  },
  {
    id: "adj_002",
    originalCalculationId: "calc_002",
    participantId: "pp_devon",
    participantName: "Devon Locke",
    type: "correction",
    amount: 25,
    reason: "Rate correction — plan effective-date interpretation",
    requestedBy: "Rose Delacroix",
    requestedAt: now,
    requiredApprover: "Owner",
    effectivePeriod: "2026-07-31",
    status: "pending_approval",
    accountingPreview: "DR Commission Expense $25 / CR Commission Payable $25",
    auditTimeline: [{ at: now, actor: "Rose Delacroix", action: "Adjustment drafted" }],
  },
];

export const MOCK_REVERSALS: CompensationReversal[] = [
  {
    id: "rev_001",
    originalCalculationId: "calc_prev_010",
    affectedLineIds: ["cl_prev_010a"],
    reversalScope: "full",
    reason: "Attribution correction — closer not eligible under plan v2",
    effectivePeriod: "2026-07-31",
    accountingImpact: "Reverse commission expense and payable; open period",
    participantImpact: "Devon Locke: -$450 net payable",
    statementImpact: "July statement adjusted; audit trail preserved",
    requestedBy: "Rose Delacroix",
    requestedAt: now,
    status: "pending_approval",
    amount: -450,
  },
];

// ─── Clawbacks ────────────────────────────────────────────────────────────

export const MOCK_CLAWBACKS: CompensationClawback[] = [
  {
    id: "cb_001",
    originalCalculationId: "calc_prev_004",
    originalPaymentId: "pay_prev_004",
    participantId: "pp_devon",
    participantName: "Devon Locke",
    trigger: "chargeback",
    grossClawback: 500,
    amountRecovered: 200,
    remainingAmount: 300,
    recoveryMethod: "offset_future_payable",
    approvalStatus: "in_recovery",
    disputeState: "none",
    accountingImpact: "DR Commission Clawback Receivable $500 / CR Commission Expense $500",
    payrollApImpact: "Offset next Devon payroll cycle up to remaining balance",
    recoveries: [
      {
        id: "rec_001",
        clawbackId: "cb_001",
        amount: 200,
        method: "offset_future_payable",
        recordedAt: now,
        recordedBy: "Accounting Lead",
      },
    ],
    createdAt: now,
    createdBy: "Accounting Lead",
    auditTimeline: [
      { at: now, actor: "Accounting Lead", action: "Clawback opened after $500 chargeback" },
      { at: now, actor: "Rose Delacroix", action: "Approved recovery via future payable offset" },
    ],
  },
  {
    id: "cb_002",
    originalCalculationId: "calc_prev_011",
    participantId: "pp_kestrel",
    participantName: "Kestrel Media",
    trigger: "partial_refund",
    grossClawback: 120,
    amountRecovered: 0,
    remainingAmount: 120,
    approvalStatus: "pending_approval",
    disputeState: "none",
    accountingImpact: "Pending — awaiting approval",
    payrollApImpact: "Pending",
    recoveries: [],
    createdAt: now,
    createdBy: "Accounting Lead",
    auditTimeline: [
      { at: now, actor: "Accounting Lead", action: "Clawback drafted from partial refund" },
    ],
  },
];

// ─── Disputes ─────────────────────────────────────────────────────────────

export const MOCK_DISPUTES: CompensationDispute[] = [
  {
    id: "disp_001",
    participantId: "pp_devon",
    participantName: "Devon Locke",
    calculationId: "calc_prev_012",
    amountInDispute: 250,
    type: "attribution",
    filedDate: "2026-07-10",
    filedBy: "Devon Locke",
    assignedReviewer: "Rose Delacroix",
    status: "leadership_review",
    slaDueDate: "2026-07-24",
    proposedResolution: "Reassign 50% to Devon as relationship creator",
    evidenceIds: ["ev_101", "ev_102"],
    auditTimeline: [
      { at: "2026-07-10T14:00:00Z", actor: "Devon Locke", action: "Dispute filed" },
      { at: now, actor: "Accounting Lead", action: "Assigned to Owner review" },
    ],
  },
  {
    id: "disp_002",
    participantId: "pp_tara",
    participantName: "Tara Casella",
    amountInDispute: 126,
    type: "post_termination_survival",
    filedDate: "2026-07-11",
    filedBy: "Tara Casella",
    assignedReviewer: "Legal",
    status: "legal_review",
    slaDueDate: "2026-07-25",
    proposedResolution: "Confirm 12-month survival applies to software NRSR",
    evidenceIds: ["ev_201"],
    auditTimeline: [{ at: "2026-07-11T14:00:00Z", actor: "Tara Casella", action: "Dispute filed" }],
  },
];

// ─── Reconciliation ──────────────────────────────────────────────────────

export const MOCK_RECONCILIATION: CompensationReconciliation = {
  periodStart: "2026-07-01",
  periodEnd: "2026-07-15",
  calculated: 2680,
  approved: 2680,
  reserved: 2680,
  payable: 2680,
  exported: 1620,
  paidExternally: 0,
  clearedInBank: 0,
  recordedInLedger: 2680,
  reflectedOnStatement: 2680,
  exceptions: [
    {
      id: "rex_001",
      type: "payable_not_scheduled",
      participantName: "Kestrel Media",
      amount: 238,
      detectedAt: now,
      description: "Payable pay_003 approved but not yet in a submitted batch",
      suggestedResolution: "Include in AP batch #002 export",
      status: "in_progress",
      assignedTo: "Accounting Lead",
    },
    {
      id: "rex_002",
      type: "statement_mismatch",
      participantName: "Priya Kapoor",
      amount: 25,
      detectedAt: now,
      description: "Pending adjustment adj_002 not yet reflected on statement",
      suggestedResolution: "Regenerate statement after approval",
      status: "open",
    },
  ],
};
