/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VendorsRouteImport } from './routes/vendors'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as PaymentsRouteImport } from './routes/payments'
import { Route as InvoicesRouteImport } from './routes/invoices'
import { Route as IntegrationsRouteImport } from './routes/integrations'
import { Route as ExpensesRouteImport } from './routes/expenses'
import { Route as EstimatesRouteImport } from './routes/estimates'
import { Route as CustomersRouteImport } from './routes/customers'
import { Route as CloseRouteImport } from './routes/close'
import { Route as CashAvailabilityRouteImport } from './routes/cash-availability'
import { Route as BillsRouteImport } from './routes/bills'
import { Route as AuditRouteImport } from './routes/audit'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InvoicesIndexRouteImport } from './routes/invoices.index'
import { Route as ExpensesIndexRouteImport } from './routes/expenses.index'
import { Route as CashAvailabilityIndexRouteImport } from './routes/cash-availability.index'
import { Route as BankingIndexRouteImport } from './routes/banking.index'
import { Route as ReadinessProductionRouteImport } from './routes/readiness.production'
import { Route as ReadinessMigrationRouteImport } from './routes/readiness.migration'
import { Route as LedgerJournalsRouteImport } from './routes/ledger.journals'
import { Route as LedgerGeneralRouteImport } from './routes/ledger.general'
import { Route as LedgerAccountsRouteImport } from './routes/ledger.accounts'
import { Route as InvoicesRecurringRouteImport } from './routes/invoices.recurring'
import { Route as InvoicesNewRouteImport } from './routes/invoices.new'
import { Route as InvoicesCreditNotesRouteImport } from './routes/invoices.credit-notes'
import { Route as InvoicesInvoiceIdRouteImport } from './routes/invoices.$invoiceId'
import { Route as ExpensesVendorsRouteImport } from './routes/expenses.vendors'
import { Route as ExpensesSubscriptionsRouteImport } from './routes/expenses.subscriptions'
import { Route as ExpensesSubmitRouteImport } from './routes/expenses.submit'
import { Route as ExpensesReportsRouteImport } from './routes/expenses.reports'
import { Route as ExpensesReimbursementsRouteImport } from './routes/expenses.reimbursements'
import { Route as ExpensesRecoveryRouteImport } from './routes/expenses.recovery'
import { Route as ExpensesReceiptsRouteImport } from './routes/expenses.receipts'
import { Route as ExpensesPreSpendRouteImport } from './routes/expenses.pre-spend'
import { Route as ExpensesPoliciesRouteImport } from './routes/expenses.policies'
import { Route as ExpensesMatchingRouteImport } from './routes/expenses.matching'
import { Route as ExpensesListRouteImport } from './routes/expenses.list'
import { Route as ExpensesIntelligenceRouteImport } from './routes/expenses.intelligence'
import { Route as ExpensesCopilotRouteImport } from './routes/expenses.copilot'
import { Route as ExpensesApprovalsRouteImport } from './routes/expenses.approvals'
import { Route as EstimatesNewRouteImport } from './routes/estimates.new'
import { Route as DashboardsTeamRouteImport } from './routes/dashboards.team'
import { Route as DashboardsReviewerRouteImport } from './routes/dashboards.reviewer'
import { Route as DashboardsAccountingRouteImport } from './routes/dashboards.accounting'
import { Route as CustomersCustomerIdRouteImport } from './routes/customers.$customerId'
import { Route as CashAvailabilityRulesRouteImport } from './routes/cash-availability.rules'
import { Route as CashAvailabilityAllocationsRouteImport } from './routes/cash-availability.allocations'
import { Route as BankingTransactionsRouteImport } from './routes/banking.transactions'
import { Route as BankingReconciliationRouteImport } from './routes/banking.reconciliation'
import { Route as AdminUsersRouteImport } from './routes/admin.users'

const VendorsRoute = VendorsRouteImport.update({
  id: '/vendors',
  path: '/vendors',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentsRoute = PaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const InvoicesRoute = InvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrationsRoute = IntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpensesRoute = ExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => rootRouteImport,
} as any)
const EstimatesRoute = EstimatesRouteImport.update({
  id: '/estimates',
  path: '/estimates',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersRoute = CustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => rootRouteImport,
} as any)
const CloseRoute = CloseRouteImport.update({
  id: '/close',
  path: '/close',
  getParentRoute: () => rootRouteImport,
} as any)
const CashAvailabilityRoute = CashAvailabilityRouteImport.update({
  id: '/cash-availability',
  path: '/cash-availability',
  getParentRoute: () => rootRouteImport,
} as any)
const BillsRoute = BillsRouteImport.update({
  id: '/bills',
  path: '/bills',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRoute = AuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InvoicesIndexRoute = InvoicesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => InvoicesRoute,
} as any)
const ExpensesIndexRoute = ExpensesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ExpensesRoute,
} as any)
const CashAvailabilityIndexRoute = CashAvailabilityIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CashAvailabilityRoute,
} as any)
const BankingIndexRoute = BankingIndexRouteImport.update({
  id: '/banking/',
  path: '/banking/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReadinessProductionRoute = ReadinessProductionRouteImport.update({
  id: '/readiness/production',
  path: '/readiness/production',
  getParentRoute: () => rootRouteImport,
} as any)
const ReadinessMigrationRoute = ReadinessMigrationRouteImport.update({
  id: '/readiness/migration',
  path: '/readiness/migration',
  getParentRoute: () => rootRouteImport,
} as any)
const LedgerJournalsRoute = LedgerJournalsRouteImport.update({
  id: '/ledger/journals',
  path: '/ledger/journals',
  getParentRoute: () => rootRouteImport,
} as any)
const LedgerGeneralRoute = LedgerGeneralRouteImport.update({
  id: '/ledger/general',
  path: '/ledger/general',
  getParentRoute: () => rootRouteImport,
} as any)
const LedgerAccountsRoute = LedgerAccountsRouteImport.update({
  id: '/ledger/accounts',
  path: '/ledger/accounts',
  getParentRoute: () => rootRouteImport,
} as any)
const InvoicesRecurringRoute = InvoicesRecurringRouteImport.update({
  id: '/recurring',
  path: '/recurring',
  getParentRoute: () => InvoicesRoute,
} as any)
const InvoicesNewRoute = InvoicesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => InvoicesRoute,
} as any)
const InvoicesCreditNotesRoute = InvoicesCreditNotesRouteImport.update({
  id: '/credit-notes',
  path: '/credit-notes',
  getParentRoute: () => InvoicesRoute,
} as any)
const InvoicesInvoiceIdRoute = InvoicesInvoiceIdRouteImport.update({
  id: '/$invoiceId',
  path: '/$invoiceId',
  getParentRoute: () => InvoicesRoute,
} as any)
const ExpensesVendorsRoute = ExpensesVendorsRouteImport.update({
  id: '/vendors',
  path: '/vendors',
  getParentRoute: () => ExpensesRoute,
} as any)
const ExpensesSubscriptionsRoute = ExpensesSubscriptionsRouteImport.update({
  id: '/subscriptions',
  path: '/subscriptions',
  getParentRoute: () => ExpensesRoute,
} as any)
const ExpensesSubmitRoute = ExpensesSubmitRouteImport.update({
  id: '/submit',
  path: '/submit',
  getParentRoute: () => ExpensesRoute,
} as any)
const ExpensesReportsRoute = ExpensesReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => ExpensesRoute,
} as any)
const ExpensesReimbursementsRoute = ExpensesReimbursementsRouteImport.update({
  id: '/reimbursements',
  path: '/reimbursements',
  getParentRoute: () => ExpensesRoute,
} as any)
const ExpensesRecoveryRoute = ExpensesRecoveryRouteImport.update({
  id: '/recovery',
  path: '/recovery',
  getParentRoute: () => ExpensesRoute,
} as any)
const ExpensesReceiptsRoute = ExpensesReceiptsRouteImport.update({
  id: '/receipts',
  path: '/receipts',
  getParentRoute: () => ExpensesRoute,
} as any)
const ExpensesPreSpendRoute = ExpensesPreSpendRouteImport.update({
  id: '/pre-spend',
  path: '/pre-spend',
  getParentRoute: () => ExpensesRoute,
} as any)
const ExpensesPoliciesRoute = ExpensesPoliciesRouteImport.update({
  id: '/policies',
  path: '/policies',
  getParentRoute: () => ExpensesRoute,
} as any)
const ExpensesMatchingRoute = ExpensesMatchingRouteImport.update({
  id: '/matching',
  path: '/matching',
  getParentRoute: () => ExpensesRoute,
} as any)
const ExpensesListRoute = ExpensesListRouteImport.update({
  id: '/list',
  path: '/list',
  getParentRoute: () => ExpensesRoute,
} as any)
const ExpensesIntelligenceRoute = ExpensesIntelligenceRouteImport.update({
  id: '/intelligence',
  path: '/intelligence',
  getParentRoute: () => ExpensesRoute,
} as any)
const ExpensesCopilotRoute = ExpensesCopilotRouteImport.update({
  id: '/copilot',
  path: '/copilot',
  getParentRoute: () => ExpensesRoute,
} as any)
const ExpensesApprovalsRoute = ExpensesApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => ExpensesRoute,
} as any)
const EstimatesNewRoute = EstimatesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => EstimatesRoute,
} as any)
const DashboardsTeamRoute = DashboardsTeamRouteImport.update({
  id: '/dashboards/team',
  path: '/dashboards/team',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardsReviewerRoute = DashboardsReviewerRouteImport.update({
  id: '/dashboards/reviewer',
  path: '/dashboards/reviewer',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardsAccountingRoute = DashboardsAccountingRouteImport.update({
  id: '/dashboards/accounting',
  path: '/dashboards/accounting',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersCustomerIdRoute = CustomersCustomerIdRouteImport.update({
  id: '/$customerId',
  path: '/$customerId',
  getParentRoute: () => CustomersRoute,
} as any)
const CashAvailabilityRulesRoute = CashAvailabilityRulesRouteImport.update({
  id: '/rules',
  path: '/rules',
  getParentRoute: () => CashAvailabilityRoute,
} as any)
const CashAvailabilityAllocationsRoute =
  CashAvailabilityAllocationsRouteImport.update({
    id: '/allocations',
    path: '/allocations',
    getParentRoute: () => CashAvailabilityRoute,
  } as any)
const BankingTransactionsRoute = BankingTransactionsRouteImport.update({
  id: '/banking/transactions',
  path: '/banking/transactions',
  getParentRoute: () => rootRouteImport,
} as any)
const BankingReconciliationRoute = BankingReconciliationRouteImport.update({
  id: '/banking/reconciliation',
  path: '/banking/reconciliation',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/bills': typeof BillsRoute
  '/cash-availability': typeof CashAvailabilityRouteWithChildren
  '/close': typeof CloseRoute
  '/customers': typeof CustomersRouteWithChildren
  '/estimates': typeof EstimatesRouteWithChildren
  '/expenses': typeof ExpensesRouteWithChildren
  '/integrations': typeof IntegrationsRoute
  '/invoices': typeof InvoicesRouteWithChildren
  '/payments': typeof PaymentsRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/vendors': typeof VendorsRoute
  '/admin/users': typeof AdminUsersRoute
  '/banking/reconciliation': typeof BankingReconciliationRoute
  '/banking/transactions': typeof BankingTransactionsRoute
  '/cash-availability/allocations': typeof CashAvailabilityAllocationsRoute
  '/cash-availability/rules': typeof CashAvailabilityRulesRoute
  '/customers/$customerId': typeof CustomersCustomerIdRoute
  '/dashboards/accounting': typeof DashboardsAccountingRoute
  '/dashboards/reviewer': typeof DashboardsReviewerRoute
  '/dashboards/team': typeof DashboardsTeamRoute
  '/estimates/new': typeof EstimatesNewRoute
  '/expenses/approvals': typeof ExpensesApprovalsRoute
  '/expenses/copilot': typeof ExpensesCopilotRoute
  '/expenses/intelligence': typeof ExpensesIntelligenceRoute
  '/expenses/list': typeof ExpensesListRoute
  '/expenses/matching': typeof ExpensesMatchingRoute
  '/expenses/policies': typeof ExpensesPoliciesRoute
  '/expenses/pre-spend': typeof ExpensesPreSpendRoute
  '/expenses/receipts': typeof ExpensesReceiptsRoute
  '/expenses/recovery': typeof ExpensesRecoveryRoute
  '/expenses/reimbursements': typeof ExpensesReimbursementsRoute
  '/expenses/reports': typeof ExpensesReportsRoute
  '/expenses/submit': typeof ExpensesSubmitRoute
  '/expenses/subscriptions': typeof ExpensesSubscriptionsRoute
  '/expenses/vendors': typeof ExpensesVendorsRoute
  '/invoices/$invoiceId': typeof InvoicesInvoiceIdRoute
  '/invoices/credit-notes': typeof InvoicesCreditNotesRoute
  '/invoices/new': typeof InvoicesNewRoute
  '/invoices/recurring': typeof InvoicesRecurringRoute
  '/ledger/accounts': typeof LedgerAccountsRoute
  '/ledger/general': typeof LedgerGeneralRoute
  '/ledger/journals': typeof LedgerJournalsRoute
  '/readiness/migration': typeof ReadinessMigrationRoute
  '/readiness/production': typeof ReadinessProductionRoute
  '/banking/': typeof BankingIndexRoute
  '/cash-availability/': typeof CashAvailabilityIndexRoute
  '/expenses/': typeof ExpensesIndexRoute
  '/invoices/': typeof InvoicesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/bills': typeof BillsRoute
  '/close': typeof CloseRoute
  '/customers': typeof CustomersRouteWithChildren
  '/estimates': typeof EstimatesRouteWithChildren
  '/integrations': typeof IntegrationsRoute
  '/payments': typeof PaymentsRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/vendors': typeof VendorsRoute
  '/admin/users': typeof AdminUsersRoute
  '/banking/reconciliation': typeof BankingReconciliationRoute
  '/banking/transactions': typeof BankingTransactionsRoute
  '/cash-availability/allocations': typeof CashAvailabilityAllocationsRoute
  '/cash-availability/rules': typeof CashAvailabilityRulesRoute
  '/customers/$customerId': typeof CustomersCustomerIdRoute
  '/dashboards/accounting': typeof DashboardsAccountingRoute
  '/dashboards/reviewer': typeof DashboardsReviewerRoute
  '/dashboards/team': typeof DashboardsTeamRoute
  '/estimates/new': typeof EstimatesNewRoute
  '/expenses/approvals': typeof ExpensesApprovalsRoute
  '/expenses/copilot': typeof ExpensesCopilotRoute
  '/expenses/intelligence': typeof ExpensesIntelligenceRoute
  '/expenses/list': typeof ExpensesListRoute
  '/expenses/matching': typeof ExpensesMatchingRoute
  '/expenses/policies': typeof ExpensesPoliciesRoute
  '/expenses/pre-spend': typeof ExpensesPreSpendRoute
  '/expenses/receipts': typeof ExpensesReceiptsRoute
  '/expenses/recovery': typeof ExpensesRecoveryRoute
  '/expenses/reimbursements': typeof ExpensesReimbursementsRoute
  '/expenses/reports': typeof ExpensesReportsRoute
  '/expenses/submit': typeof ExpensesSubmitRoute
  '/expenses/subscriptions': typeof ExpensesSubscriptionsRoute
  '/expenses/vendors': typeof ExpensesVendorsRoute
  '/invoices/$invoiceId': typeof InvoicesInvoiceIdRoute
  '/invoices/credit-notes': typeof InvoicesCreditNotesRoute
  '/invoices/new': typeof InvoicesNewRoute
  '/invoices/recurring': typeof InvoicesRecurringRoute
  '/ledger/accounts': typeof LedgerAccountsRoute
  '/ledger/general': typeof LedgerGeneralRoute
  '/ledger/journals': typeof LedgerJournalsRoute
  '/readiness/migration': typeof ReadinessMigrationRoute
  '/readiness/production': typeof ReadinessProductionRoute
  '/banking': typeof BankingIndexRoute
  '/cash-availability': typeof CashAvailabilityIndexRoute
  '/expenses': typeof ExpensesIndexRoute
  '/invoices': typeof InvoicesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/bills': typeof BillsRoute
  '/cash-availability': typeof CashAvailabilityRouteWithChildren
  '/close': typeof CloseRoute
  '/customers': typeof CustomersRouteWithChildren
  '/estimates': typeof EstimatesRouteWithChildren
  '/expenses': typeof ExpensesRouteWithChildren
  '/integrations': typeof IntegrationsRoute
  '/invoices': typeof InvoicesRouteWithChildren
  '/payments': typeof PaymentsRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/vendors': typeof VendorsRoute
  '/admin/users': typeof AdminUsersRoute
  '/banking/reconciliation': typeof BankingReconciliationRoute
  '/banking/transactions': typeof BankingTransactionsRoute
  '/cash-availability/allocations': typeof CashAvailabilityAllocationsRoute
  '/cash-availability/rules': typeof CashAvailabilityRulesRoute
  '/customers/$customerId': typeof CustomersCustomerIdRoute
  '/dashboards/accounting': typeof DashboardsAccountingRoute
  '/dashboards/reviewer': typeof DashboardsReviewerRoute
  '/dashboards/team': typeof DashboardsTeamRoute
  '/estimates/new': typeof EstimatesNewRoute
  '/expenses/approvals': typeof ExpensesApprovalsRoute
  '/expenses/copilot': typeof ExpensesCopilotRoute
  '/expenses/intelligence': typeof ExpensesIntelligenceRoute
  '/expenses/list': typeof ExpensesListRoute
  '/expenses/matching': typeof ExpensesMatchingRoute
  '/expenses/policies': typeof ExpensesPoliciesRoute
  '/expenses/pre-spend': typeof ExpensesPreSpendRoute
  '/expenses/receipts': typeof ExpensesReceiptsRoute
  '/expenses/recovery': typeof ExpensesRecoveryRoute
  '/expenses/reimbursements': typeof ExpensesReimbursementsRoute
  '/expenses/reports': typeof ExpensesReportsRoute
  '/expenses/submit': typeof ExpensesSubmitRoute
  '/expenses/subscriptions': typeof ExpensesSubscriptionsRoute
  '/expenses/vendors': typeof ExpensesVendorsRoute
  '/invoices/$invoiceId': typeof InvoicesInvoiceIdRoute
  '/invoices/credit-notes': typeof InvoicesCreditNotesRoute
  '/invoices/new': typeof InvoicesNewRoute
  '/invoices/recurring': typeof InvoicesRecurringRoute
  '/ledger/accounts': typeof LedgerAccountsRoute
  '/ledger/general': typeof LedgerGeneralRoute
  '/ledger/journals': typeof LedgerJournalsRoute
  '/readiness/migration': typeof ReadinessMigrationRoute
  '/readiness/production': typeof ReadinessProductionRoute
  '/banking/': typeof BankingIndexRoute
  '/cash-availability/': typeof CashAvailabilityIndexRoute
  '/expenses/': typeof ExpensesIndexRoute
  '/invoices/': typeof InvoicesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/audit'
    | '/bills'
    | '/cash-availability'
    | '/close'
    | '/customers'
    | '/estimates'
    | '/expenses'
    | '/integrations'
    | '/invoices'
    | '/payments'
    | '/reports'
    | '/settings'
    | '/vendors'
    | '/admin/users'
    | '/banking/reconciliation'
    | '/banking/transactions'
    | '/cash-availability/allocations'
    | '/cash-availability/rules'
    | '/customers/$customerId'
    | '/dashboards/accounting'
    | '/dashboards/reviewer'
    | '/dashboards/team'
    | '/estimates/new'
    | '/expenses/approvals'
    | '/expenses/copilot'
    | '/expenses/intelligence'
    | '/expenses/list'
    | '/expenses/matching'
    | '/expenses/policies'
    | '/expenses/pre-spend'
    | '/expenses/receipts'
    | '/expenses/recovery'
    | '/expenses/reimbursements'
    | '/expenses/reports'
    | '/expenses/submit'
    | '/expenses/subscriptions'
    | '/expenses/vendors'
    | '/invoices/$invoiceId'
    | '/invoices/credit-notes'
    | '/invoices/new'
    | '/invoices/recurring'
    | '/ledger/accounts'
    | '/ledger/general'
    | '/ledger/journals'
    | '/readiness/migration'
    | '/readiness/production'
    | '/banking/'
    | '/cash-availability/'
    | '/expenses/'
    | '/invoices/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/audit'
    | '/bills'
    | '/close'
    | '/customers'
    | '/estimates'
    | '/integrations'
    | '/payments'
    | '/reports'
    | '/settings'
    | '/vendors'
    | '/admin/users'
    | '/banking/reconciliation'
    | '/banking/transactions'
    | '/cash-availability/allocations'
    | '/cash-availability/rules'
    | '/customers/$customerId'
    | '/dashboards/accounting'
    | '/dashboards/reviewer'
    | '/dashboards/team'
    | '/estimates/new'
    | '/expenses/approvals'
    | '/expenses/copilot'
    | '/expenses/intelligence'
    | '/expenses/list'
    | '/expenses/matching'
    | '/expenses/policies'
    | '/expenses/pre-spend'
    | '/expenses/receipts'
    | '/expenses/recovery'
    | '/expenses/reimbursements'
    | '/expenses/reports'
    | '/expenses/submit'
    | '/expenses/subscriptions'
    | '/expenses/vendors'
    | '/invoices/$invoiceId'
    | '/invoices/credit-notes'
    | '/invoices/new'
    | '/invoices/recurring'
    | '/ledger/accounts'
    | '/ledger/general'
    | '/ledger/journals'
    | '/readiness/migration'
    | '/readiness/production'
    | '/banking'
    | '/cash-availability'
    | '/expenses'
    | '/invoices'
  id:
    | '__root__'
    | '/'
    | '/audit'
    | '/bills'
    | '/cash-availability'
    | '/close'
    | '/customers'
    | '/estimates'
    | '/expenses'
    | '/integrations'
    | '/invoices'
    | '/payments'
    | '/reports'
    | '/settings'
    | '/vendors'
    | '/admin/users'
    | '/banking/reconciliation'
    | '/banking/transactions'
    | '/cash-availability/allocations'
    | '/cash-availability/rules'
    | '/customers/$customerId'
    | '/dashboards/accounting'
    | '/dashboards/reviewer'
    | '/dashboards/team'
    | '/estimates/new'
    | '/expenses/approvals'
    | '/expenses/copilot'
    | '/expenses/intelligence'
    | '/expenses/list'
    | '/expenses/matching'
    | '/expenses/policies'
    | '/expenses/pre-spend'
    | '/expenses/receipts'
    | '/expenses/recovery'
    | '/expenses/reimbursements'
    | '/expenses/reports'
    | '/expenses/submit'
    | '/expenses/subscriptions'
    | '/expenses/vendors'
    | '/invoices/$invoiceId'
    | '/invoices/credit-notes'
    | '/invoices/new'
    | '/invoices/recurring'
    | '/ledger/accounts'
    | '/ledger/general'
    | '/ledger/journals'
    | '/readiness/migration'
    | '/readiness/production'
    | '/banking/'
    | '/cash-availability/'
    | '/expenses/'
    | '/invoices/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuditRoute: typeof AuditRoute
  BillsRoute: typeof BillsRoute
  CashAvailabilityRoute: typeof CashAvailabilityRouteWithChildren
  CloseRoute: typeof CloseRoute
  CustomersRoute: typeof CustomersRouteWithChildren
  EstimatesRoute: typeof EstimatesRouteWithChildren
  ExpensesRoute: typeof ExpensesRouteWithChildren
  IntegrationsRoute: typeof IntegrationsRoute
  InvoicesRoute: typeof InvoicesRouteWithChildren
  PaymentsRoute: typeof PaymentsRoute
  ReportsRoute: typeof ReportsRoute
  SettingsRoute: typeof SettingsRoute
  VendorsRoute: typeof VendorsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  BankingReconciliationRoute: typeof BankingReconciliationRoute
  BankingTransactionsRoute: typeof BankingTransactionsRoute
  DashboardsAccountingRoute: typeof DashboardsAccountingRoute
  DashboardsReviewerRoute: typeof DashboardsReviewerRoute
  DashboardsTeamRoute: typeof DashboardsTeamRoute
  LedgerAccountsRoute: typeof LedgerAccountsRoute
  LedgerGeneralRoute: typeof LedgerGeneralRoute
  LedgerJournalsRoute: typeof LedgerJournalsRoute
  ReadinessMigrationRoute: typeof ReadinessMigrationRoute
  ReadinessProductionRoute: typeof ReadinessProductionRoute
  BankingIndexRoute: typeof BankingIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vendors': {
      id: '/vendors'
      path: '/vendors'
      fullPath: '/vendors'
      preLoaderRoute: typeof VendorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payments': {
      id: '/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof PaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invoices': {
      id: '/invoices'
      path: '/invoices'
      fullPath: '/invoices'
      preLoaderRoute: typeof InvoicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integrations': {
      id: '/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof IntegrationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expenses': {
      id: '/expenses'
      path: '/expenses'
      fullPath: '/expenses'
      preLoaderRoute: typeof ExpensesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estimates': {
      id: '/estimates'
      path: '/estimates'
      fullPath: '/estimates'
      preLoaderRoute: typeof EstimatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers': {
      id: '/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof CustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/close': {
      id: '/close'
      path: '/close'
      fullPath: '/close'
      preLoaderRoute: typeof CloseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cash-availability': {
      id: '/cash-availability'
      path: '/cash-availability'
      fullPath: '/cash-availability'
      preLoaderRoute: typeof CashAvailabilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bills': {
      id: '/bills'
      path: '/bills'
      fullPath: '/bills'
      preLoaderRoute: typeof BillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit': {
      id: '/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invoices/': {
      id: '/invoices/'
      path: '/'
      fullPath: '/invoices/'
      preLoaderRoute: typeof InvoicesIndexRouteImport
      parentRoute: typeof InvoicesRoute
    }
    '/expenses/': {
      id: '/expenses/'
      path: '/'
      fullPath: '/expenses/'
      preLoaderRoute: typeof ExpensesIndexRouteImport
      parentRoute: typeof ExpensesRoute
    }
    '/cash-availability/': {
      id: '/cash-availability/'
      path: '/'
      fullPath: '/cash-availability/'
      preLoaderRoute: typeof CashAvailabilityIndexRouteImport
      parentRoute: typeof CashAvailabilityRoute
    }
    '/banking/': {
      id: '/banking/'
      path: '/banking'
      fullPath: '/banking/'
      preLoaderRoute: typeof BankingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/readiness/production': {
      id: '/readiness/production'
      path: '/readiness/production'
      fullPath: '/readiness/production'
      preLoaderRoute: typeof ReadinessProductionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/readiness/migration': {
      id: '/readiness/migration'
      path: '/readiness/migration'
      fullPath: '/readiness/migration'
      preLoaderRoute: typeof ReadinessMigrationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ledger/journals': {
      id: '/ledger/journals'
      path: '/ledger/journals'
      fullPath: '/ledger/journals'
      preLoaderRoute: typeof LedgerJournalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ledger/general': {
      id: '/ledger/general'
      path: '/ledger/general'
      fullPath: '/ledger/general'
      preLoaderRoute: typeof LedgerGeneralRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ledger/accounts': {
      id: '/ledger/accounts'
      path: '/ledger/accounts'
      fullPath: '/ledger/accounts'
      preLoaderRoute: typeof LedgerAccountsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invoices/recurring': {
      id: '/invoices/recurring'
      path: '/recurring'
      fullPath: '/invoices/recurring'
      preLoaderRoute: typeof InvoicesRecurringRouteImport
      parentRoute: typeof InvoicesRoute
    }
    '/invoices/new': {
      id: '/invoices/new'
      path: '/new'
      fullPath: '/invoices/new'
      preLoaderRoute: typeof InvoicesNewRouteImport
      parentRoute: typeof InvoicesRoute
    }
    '/invoices/credit-notes': {
      id: '/invoices/credit-notes'
      path: '/credit-notes'
      fullPath: '/invoices/credit-notes'
      preLoaderRoute: typeof InvoicesCreditNotesRouteImport
      parentRoute: typeof InvoicesRoute
    }
    '/invoices/$invoiceId': {
      id: '/invoices/$invoiceId'
      path: '/$invoiceId'
      fullPath: '/invoices/$invoiceId'
      preLoaderRoute: typeof InvoicesInvoiceIdRouteImport
      parentRoute: typeof InvoicesRoute
    }
    '/expenses/vendors': {
      id: '/expenses/vendors'
      path: '/vendors'
      fullPath: '/expenses/vendors'
      preLoaderRoute: typeof ExpensesVendorsRouteImport
      parentRoute: typeof ExpensesRoute
    }
    '/expenses/subscriptions': {
      id: '/expenses/subscriptions'
      path: '/subscriptions'
      fullPath: '/expenses/subscriptions'
      preLoaderRoute: typeof ExpensesSubscriptionsRouteImport
      parentRoute: typeof ExpensesRoute
    }
    '/expenses/submit': {
      id: '/expenses/submit'
      path: '/submit'
      fullPath: '/expenses/submit'
      preLoaderRoute: typeof ExpensesSubmitRouteImport
      parentRoute: typeof ExpensesRoute
    }
    '/expenses/reports': {
      id: '/expenses/reports'
      path: '/reports'
      fullPath: '/expenses/reports'
      preLoaderRoute: typeof ExpensesReportsRouteImport
      parentRoute: typeof ExpensesRoute
    }
    '/expenses/reimbursements': {
      id: '/expenses/reimbursements'
      path: '/reimbursements'
      fullPath: '/expenses/reimbursements'
      preLoaderRoute: typeof ExpensesReimbursementsRouteImport
      parentRoute: typeof ExpensesRoute
    }
    '/expenses/recovery': {
      id: '/expenses/recovery'
      path: '/recovery'
      fullPath: '/expenses/recovery'
      preLoaderRoute: typeof ExpensesRecoveryRouteImport
      parentRoute: typeof ExpensesRoute
    }
    '/expenses/receipts': {
      id: '/expenses/receipts'
      path: '/receipts'
      fullPath: '/expenses/receipts'
      preLoaderRoute: typeof ExpensesReceiptsRouteImport
      parentRoute: typeof ExpensesRoute
    }
    '/expenses/pre-spend': {
      id: '/expenses/pre-spend'
      path: '/pre-spend'
      fullPath: '/expenses/pre-spend'
      preLoaderRoute: typeof ExpensesPreSpendRouteImport
      parentRoute: typeof ExpensesRoute
    }
    '/expenses/policies': {
      id: '/expenses/policies'
      path: '/policies'
      fullPath: '/expenses/policies'
      preLoaderRoute: typeof ExpensesPoliciesRouteImport
      parentRoute: typeof ExpensesRoute
    }
    '/expenses/matching': {
      id: '/expenses/matching'
      path: '/matching'
      fullPath: '/expenses/matching'
      preLoaderRoute: typeof ExpensesMatchingRouteImport
      parentRoute: typeof ExpensesRoute
    }
    '/expenses/list': {
      id: '/expenses/list'
      path: '/list'
      fullPath: '/expenses/list'
      preLoaderRoute: typeof ExpensesListRouteImport
      parentRoute: typeof ExpensesRoute
    }
    '/expenses/intelligence': {
      id: '/expenses/intelligence'
      path: '/intelligence'
      fullPath: '/expenses/intelligence'
      preLoaderRoute: typeof ExpensesIntelligenceRouteImport
      parentRoute: typeof ExpensesRoute
    }
    '/expenses/copilot': {
      id: '/expenses/copilot'
      path: '/copilot'
      fullPath: '/expenses/copilot'
      preLoaderRoute: typeof ExpensesCopilotRouteImport
      parentRoute: typeof ExpensesRoute
    }
    '/expenses/approvals': {
      id: '/expenses/approvals'
      path: '/approvals'
      fullPath: '/expenses/approvals'
      preLoaderRoute: typeof ExpensesApprovalsRouteImport
      parentRoute: typeof ExpensesRoute
    }
    '/estimates/new': {
      id: '/estimates/new'
      path: '/new'
      fullPath: '/estimates/new'
      preLoaderRoute: typeof EstimatesNewRouteImport
      parentRoute: typeof EstimatesRoute
    }
    '/dashboards/team': {
      id: '/dashboards/team'
      path: '/dashboards/team'
      fullPath: '/dashboards/team'
      preLoaderRoute: typeof DashboardsTeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboards/reviewer': {
      id: '/dashboards/reviewer'
      path: '/dashboards/reviewer'
      fullPath: '/dashboards/reviewer'
      preLoaderRoute: typeof DashboardsReviewerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboards/accounting': {
      id: '/dashboards/accounting'
      path: '/dashboards/accounting'
      fullPath: '/dashboards/accounting'
      preLoaderRoute: typeof DashboardsAccountingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers/$customerId': {
      id: '/customers/$customerId'
      path: '/$customerId'
      fullPath: '/customers/$customerId'
      preLoaderRoute: typeof CustomersCustomerIdRouteImport
      parentRoute: typeof CustomersRoute
    }
    '/cash-availability/rules': {
      id: '/cash-availability/rules'
      path: '/rules'
      fullPath: '/cash-availability/rules'
      preLoaderRoute: typeof CashAvailabilityRulesRouteImport
      parentRoute: typeof CashAvailabilityRoute
    }
    '/cash-availability/allocations': {
      id: '/cash-availability/allocations'
      path: '/allocations'
      fullPath: '/cash-availability/allocations'
      preLoaderRoute: typeof CashAvailabilityAllocationsRouteImport
      parentRoute: typeof CashAvailabilityRoute
    }
    '/banking/transactions': {
      id: '/banking/transactions'
      path: '/banking/transactions'
      fullPath: '/banking/transactions'
      preLoaderRoute: typeof BankingTransactionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/banking/reconciliation': {
      id: '/banking/reconciliation'
      path: '/banking/reconciliation'
      fullPath: '/banking/reconciliation'
      preLoaderRoute: typeof BankingReconciliationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface CashAvailabilityRouteChildren {
  CashAvailabilityAllocationsRoute: typeof CashAvailabilityAllocationsRoute
  CashAvailabilityRulesRoute: typeof CashAvailabilityRulesRoute
  CashAvailabilityIndexRoute: typeof CashAvailabilityIndexRoute
}

const CashAvailabilityRouteChildren: CashAvailabilityRouteChildren = {
  CashAvailabilityAllocationsRoute: CashAvailabilityAllocationsRoute,
  CashAvailabilityRulesRoute: CashAvailabilityRulesRoute,
  CashAvailabilityIndexRoute: CashAvailabilityIndexRoute,
}

const CashAvailabilityRouteWithChildren =
  CashAvailabilityRoute._addFileChildren(CashAvailabilityRouteChildren)

interface CustomersRouteChildren {
  CustomersCustomerIdRoute: typeof CustomersCustomerIdRoute
}

const CustomersRouteChildren: CustomersRouteChildren = {
  CustomersCustomerIdRoute: CustomersCustomerIdRoute,
}

const CustomersRouteWithChildren = CustomersRoute._addFileChildren(
  CustomersRouteChildren,
)

interface EstimatesRouteChildren {
  EstimatesNewRoute: typeof EstimatesNewRoute
}

const EstimatesRouteChildren: EstimatesRouteChildren = {
  EstimatesNewRoute: EstimatesNewRoute,
}

const EstimatesRouteWithChildren = EstimatesRoute._addFileChildren(
  EstimatesRouteChildren,
)

interface ExpensesRouteChildren {
  ExpensesApprovalsRoute: typeof ExpensesApprovalsRoute
  ExpensesCopilotRoute: typeof ExpensesCopilotRoute
  ExpensesIntelligenceRoute: typeof ExpensesIntelligenceRoute
  ExpensesListRoute: typeof ExpensesListRoute
  ExpensesMatchingRoute: typeof ExpensesMatchingRoute
  ExpensesPoliciesRoute: typeof ExpensesPoliciesRoute
  ExpensesPreSpendRoute: typeof ExpensesPreSpendRoute
  ExpensesReceiptsRoute: typeof ExpensesReceiptsRoute
  ExpensesRecoveryRoute: typeof ExpensesRecoveryRoute
  ExpensesReimbursementsRoute: typeof ExpensesReimbursementsRoute
  ExpensesReportsRoute: typeof ExpensesReportsRoute
  ExpensesSubmitRoute: typeof ExpensesSubmitRoute
  ExpensesSubscriptionsRoute: typeof ExpensesSubscriptionsRoute
  ExpensesVendorsRoute: typeof ExpensesVendorsRoute
  ExpensesIndexRoute: typeof ExpensesIndexRoute
}

const ExpensesRouteChildren: ExpensesRouteChildren = {
  ExpensesApprovalsRoute: ExpensesApprovalsRoute,
  ExpensesCopilotRoute: ExpensesCopilotRoute,
  ExpensesIntelligenceRoute: ExpensesIntelligenceRoute,
  ExpensesListRoute: ExpensesListRoute,
  ExpensesMatchingRoute: ExpensesMatchingRoute,
  ExpensesPoliciesRoute: ExpensesPoliciesRoute,
  ExpensesPreSpendRoute: ExpensesPreSpendRoute,
  ExpensesReceiptsRoute: ExpensesReceiptsRoute,
  ExpensesRecoveryRoute: ExpensesRecoveryRoute,
  ExpensesReimbursementsRoute: ExpensesReimbursementsRoute,
  ExpensesReportsRoute: ExpensesReportsRoute,
  ExpensesSubmitRoute: ExpensesSubmitRoute,
  ExpensesSubscriptionsRoute: ExpensesSubscriptionsRoute,
  ExpensesVendorsRoute: ExpensesVendorsRoute,
  ExpensesIndexRoute: ExpensesIndexRoute,
}

const ExpensesRouteWithChildren = ExpensesRoute._addFileChildren(
  ExpensesRouteChildren,
)

interface InvoicesRouteChildren {
  InvoicesInvoiceIdRoute: typeof InvoicesInvoiceIdRoute
  InvoicesCreditNotesRoute: typeof InvoicesCreditNotesRoute
  InvoicesNewRoute: typeof InvoicesNewRoute
  InvoicesRecurringRoute: typeof InvoicesRecurringRoute
  InvoicesIndexRoute: typeof InvoicesIndexRoute
}

const InvoicesRouteChildren: InvoicesRouteChildren = {
  InvoicesInvoiceIdRoute: InvoicesInvoiceIdRoute,
  InvoicesCreditNotesRoute: InvoicesCreditNotesRoute,
  InvoicesNewRoute: InvoicesNewRoute,
  InvoicesRecurringRoute: InvoicesRecurringRoute,
  InvoicesIndexRoute: InvoicesIndexRoute,
}

const InvoicesRouteWithChildren = InvoicesRoute._addFileChildren(
  InvoicesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuditRoute: AuditRoute,
  BillsRoute: BillsRoute,
  CashAvailabilityRoute: CashAvailabilityRouteWithChildren,
  CloseRoute: CloseRoute,
  CustomersRoute: CustomersRouteWithChildren,
  EstimatesRoute: EstimatesRouteWithChildren,
  ExpensesRoute: ExpensesRouteWithChildren,
  IntegrationsRoute: IntegrationsRoute,
  InvoicesRoute: InvoicesRouteWithChildren,
  PaymentsRoute: PaymentsRoute,
  ReportsRoute: ReportsRoute,
  SettingsRoute: SettingsRoute,
  VendorsRoute: VendorsRoute,
  AdminUsersRoute: AdminUsersRoute,
  BankingReconciliationRoute: BankingReconciliationRoute,
  BankingTransactionsRoute: BankingTransactionsRoute,
  DashboardsAccountingRoute: DashboardsAccountingRoute,
  DashboardsReviewerRoute: DashboardsReviewerRoute,
  DashboardsTeamRoute: DashboardsTeamRoute,
  LedgerAccountsRoute: LedgerAccountsRoute,
  LedgerGeneralRoute: LedgerGeneralRoute,
  LedgerJournalsRoute: LedgerJournalsRoute,
  ReadinessMigrationRoute: ReadinessMigrationRoute,
  ReadinessProductionRoute: ReadinessProductionRoute,
  BankingIndexRoute: BankingIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
