
-- M9B — Intelligence Services Layer
-- Advisory-only intelligence built on top of the Canonical Metrics Layer.
-- AI cannot modify metrics, post transactions, or approve accounting actions.

-- ============================================================
-- financial_anomalies
-- Detected deviations in canonical metrics (or their sources).
-- Every row is advisory only and immutable on narrative/evidence.
-- ============================================================
CREATE TABLE public.financial_anomalies (
  id UUID NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  org_id UUID NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
  metric_key TEXT NOT NULL,
  metric_id UUID REFERENCES public.financial_metrics(id) ON DELETE SET NULL,
  detector TEXT NOT NULL DEFAULT 'threshold',              -- 'threshold' | 'zscore' | 'trend' | 'ratio' | 'custom'
  severity TEXT NOT NULL DEFAULT 'medium' CHECK (severity IN ('low','medium','high','critical')),
  status TEXT NOT NULL DEFAULT 'open' CHECK (status IN ('open','acknowledged','dismissed','resolved')),
  title TEXT NOT NULL,
  narrative TEXT NOT NULL,
  observed_value NUMERIC,
  expected_value NUMERIC,
  deviation NUMERIC,
  period_start DATE,
  period_end DATE,
  evidence JSONB NOT NULL DEFAULT '[]'::jsonb,
  confidence NUMERIC NOT NULL DEFAULT 0.5 CHECK (confidence >= 0 AND confidence <= 1),
  freshness TEXT NOT NULL DEFAULT 'fresh' CHECK (freshness IN ('fresh','delayed','stale','unavailable')),
  assumptions TEXT[] NOT NULL DEFAULT '{}',
  missing_data TEXT[] NOT NULL DEFAULT '{}',
  recommended_action TEXT,
  approval_requirement TEXT,
  advisory_only BOOLEAN NOT NULL DEFAULT TRUE,
  demonstration_only BOOLEAN NOT NULL DEFAULT FALSE,
  acknowledged_by UUID REFERENCES auth.users(id),
  acknowledged_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_financial_anomalies_org_status ON public.financial_anomalies (org_id, status, created_at DESC);
CREATE INDEX idx_financial_anomalies_metric ON public.financial_anomalies (org_id, metric_key);

GRANT SELECT, INSERT, UPDATE ON public.financial_anomalies TO authenticated;
GRANT ALL ON public.financial_anomalies TO service_role;

ALTER TABLE public.financial_anomalies ENABLE ROW LEVEL SECURITY;

CREATE POLICY "anomalies_select_org" ON public.financial_anomalies
  FOR SELECT TO authenticated USING (public.is_org_member(org_id));
CREATE POLICY "anomalies_status_update" ON public.financial_anomalies
  FOR UPDATE TO authenticated
  USING (public.is_org_member(org_id))
  WITH CHECK (public.is_org_member(org_id));
-- No client INSERT policy — anomalies are generated by service_role only.

-- Immutability trigger: narrative/evidence/confidence/advisory_only cannot change.
CREATE OR REPLACE FUNCTION public.tg_anomalies_advisory_guard()
RETURNS TRIGGER LANGUAGE plpgsql SET search_path = public AS $$
BEGIN
  IF TG_OP = 'UPDATE' THEN
    IF NEW.narrative        IS DISTINCT FROM OLD.narrative
    OR NEW.evidence         IS DISTINCT FROM OLD.evidence
    OR NEW.confidence       IS DISTINCT FROM OLD.confidence
    OR NEW.advisory_only    IS DISTINCT FROM OLD.advisory_only
    OR NEW.observed_value   IS DISTINCT FROM OLD.observed_value
    OR NEW.expected_value   IS DISTINCT FROM OLD.expected_value THEN
      RAISE EXCEPTION 'Anomaly narrative/evidence/confidence is immutable (advisory only).';
    END IF;
    NEW.updated_at := now();
  END IF;
  RETURN NEW;
END;
$$;
CREATE TRIGGER tg_anomalies_advisory_guard
BEFORE UPDATE ON public.financial_anomalies
FOR EACH ROW EXECUTE FUNCTION public.tg_anomalies_advisory_guard();


-- ============================================================
-- financial_recommendations
-- AI-generated recommendations. Advisory only; state machine tracks
-- human decisions (accept / dismiss / convert to task).
-- ============================================================
CREATE TABLE public.financial_recommendations (
  id UUID NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  org_id UUID NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
  category TEXT NOT NULL,                                 -- reduce_cost | recover_revenue | improve_collection | ...
  persona TEXT NOT NULL DEFAULT 'controller',             -- controller | close_assistant | accountant_assistant
  title TEXT NOT NULL,
  narrative TEXT NOT NULL,
  evidence JSONB NOT NULL DEFAULT '[]'::jsonb,
  supporting_metric_keys TEXT[] NOT NULL DEFAULT '{}',
  related_anomaly_id UUID REFERENCES public.financial_anomalies(id) ON DELETE SET NULL,
  confidence NUMERIC NOT NULL DEFAULT 0.5 CHECK (confidence >= 0 AND confidence <= 1),
  estimated_impact TEXT,
  impact_value NUMERIC,
  risk TEXT NOT NULL DEFAULT 'low' CHECK (risk IN ('low','medium','high')),
  time_horizon TEXT,
  owner_role TEXT,
  approval_requirement TEXT NOT NULL DEFAULT 'accounting_lead',
  state TEXT NOT NULL DEFAULT 'generated' CHECK (state IN (
    'generated','needs_review','accepted','dismissed',
    'converted_to_task','converted_to_draft','approved_for_action',
    'completed','outcome_measured'
  )),
  outcome_note TEXT,
  outcome_value NUMERIC,
  assumptions TEXT[] NOT NULL DEFAULT '{}',
  missing_data TEXT[] NOT NULL DEFAULT '{}',
  freshness TEXT NOT NULL DEFAULT 'fresh' CHECK (freshness IN ('fresh','delayed','stale','unavailable')),
  advisory_only BOOLEAN NOT NULL DEFAULT TRUE,
  demonstration_only BOOLEAN NOT NULL DEFAULT FALSE,
  reviewed_by UUID REFERENCES auth.users(id),
  reviewed_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_financial_recommendations_org_state ON public.financial_recommendations (org_id, state, created_at DESC);
CREATE INDEX idx_financial_recommendations_persona ON public.financial_recommendations (org_id, persona);

GRANT SELECT, INSERT, UPDATE ON public.financial_recommendations TO authenticated;
GRANT ALL ON public.financial_recommendations TO service_role;

ALTER TABLE public.financial_recommendations ENABLE ROW LEVEL SECURITY;

CREATE POLICY "recs_select_org" ON public.financial_recommendations
  FOR SELECT TO authenticated USING (public.is_org_member(org_id));
CREATE POLICY "recs_state_update" ON public.financial_recommendations
  FOR UPDATE TO authenticated
  USING (public.is_org_member(org_id))
  WITH CHECK (public.is_org_member(org_id));
-- No client INSERT policy — recommendations are generated by service_role only.

-- Immutability: narrative/evidence/confidence/advisory_only cannot change.
CREATE OR REPLACE FUNCTION public.tg_recs_advisory_guard()
RETURNS TRIGGER LANGUAGE plpgsql SET search_path = public AS $$
BEGIN
  IF TG_OP = 'UPDATE' THEN
    IF NEW.narrative     IS DISTINCT FROM OLD.narrative
    OR NEW.evidence      IS DISTINCT FROM OLD.evidence
    OR NEW.confidence    IS DISTINCT FROM OLD.confidence
    OR NEW.advisory_only IS DISTINCT FROM OLD.advisory_only
    OR NEW.category      IS DISTINCT FROM OLD.category THEN
      RAISE EXCEPTION 'Recommendation narrative/evidence/confidence is immutable (advisory only).';
    END IF;
    NEW.updated_at := now();
  END IF;
  RETURN NEW;
END;
$$;
CREATE TRIGGER tg_recs_advisory_guard
BEFORE UPDATE ON public.financial_recommendations
FOR EACH ROW EXECUTE FUNCTION public.tg_recs_advisory_guard();


-- ============================================================
-- intelligence_explanations
-- Human-readable answers to "what happened / why / evidence".
-- Every explanation carries the AI response contract.
-- ============================================================
CREATE TABLE public.intelligence_explanations (
  id UUID NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  org_id UUID NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
  subject_type TEXT NOT NULL,             -- 'metric' | 'anomaly' | 'recommendation' | 'question'
  subject_key TEXT NOT NULL,              -- metric_key | anomaly_id | recommendation_id | free-form
  question TEXT,
  answer TEXT NOT NULL,
  evidence JSONB NOT NULL DEFAULT '[]'::jsonb,
  supporting_metric_keys TEXT[] NOT NULL DEFAULT '{}',
  confidence NUMERIC NOT NULL DEFAULT 0.5 CHECK (confidence >= 0 AND confidence <= 1),
  freshness TEXT NOT NULL DEFAULT 'fresh' CHECK (freshness IN ('fresh','delayed','stale','unavailable')),
  assumptions TEXT[] NOT NULL DEFAULT '{}',
  missing_data TEXT[] NOT NULL DEFAULT '{}',
  recommended_action TEXT,
  approval_requirement TEXT,
  advisory_only BOOLEAN NOT NULL DEFAULT TRUE,
  demonstration_only BOOLEAN NOT NULL DEFAULT FALSE,
  created_by UUID REFERENCES auth.users(id),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_intelligence_explanations_org_subject
  ON public.intelligence_explanations (org_id, subject_type, subject_key, created_at DESC);

GRANT SELECT, INSERT ON public.intelligence_explanations TO authenticated;
GRANT ALL ON public.intelligence_explanations TO service_role;

ALTER TABLE public.intelligence_explanations ENABLE ROW LEVEL SECURITY;

CREATE POLICY "expl_select_org" ON public.intelligence_explanations
  FOR SELECT TO authenticated USING (public.is_org_member(org_id));
CREATE POLICY "expl_insert_org" ON public.intelligence_explanations
  FOR INSERT TO authenticated
  WITH CHECK (public.is_org_member(org_id) AND advisory_only = TRUE);

-- Explanations are append-only (no UPDATE policy).
CREATE OR REPLACE FUNCTION public.tg_expl_immutable()
RETURNS TRIGGER LANGUAGE plpgsql SET search_path = public AS $$
BEGIN
  RAISE EXCEPTION 'Intelligence explanations are append-only.';
END;
$$;
CREATE TRIGGER tg_expl_immutable
BEFORE UPDATE ON public.intelligence_explanations
FOR EACH ROW EXECUTE FUNCTION public.tg_expl_immutable();
